<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\folder\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_file_list".
 *
 * @property integer $id
 * @property integer $folder_id
 * @property integer $file_id
 * @property integer $is_folder
 * @property string $file_name
 * @property string $file_url
 * @property string $customer_id
 * @property string $aliasModel
 */
abstract class FileList extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_file_list';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            /*[['id'], 'required'],
            [['id', 'file_id'], 'integer'],
            [['is_folder'], 'string', 'max' => 4],
            [['file_name', 'customer_id'], 'string', 'max' => 100],
            [['file_url'], 'string', 'max' => 255],
            [['id'], 'unique']*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file_id' => 'File ID',
            'is_folder' => 'Is Folder',
            'file_name' => 'File Name',
            'file_url' => 'File Url',
            'customer_id' => 'Customer ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'file_id' => '文件id',
            'is_folder' => '是否为文件夹 1是',
            'file_name' => '文件或文件夹名称',
            'file_url' => '文件或文件夹位置',
            'customer_id' => '客户id',
        ]);
    }




}
