<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\teach\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_education".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\teach\OhrmEmpEducation[] $ohrmEmpEducations
 * @property string $aliasModel
 */
abstract class Education extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_education';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmpEducations()
    {
        return $this->hasMany(\common\models\teach\OhrmEmpEducation::className(), ['education_id' => 'id']);
    }




}
