<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\system\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_latitude_longitude".
 *
 * @property integer $id
 * @property string $latitude
 * @property string $longitude
 * @property integer $punching_range
 * @property integer $work_station
 * @property string $aliasModel
 */
abstract class LatitudeLongitude extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_latitude_longitude';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitude', 'longitude'], 'required'],
            [['punching_range', 'work_station'], 'integer'],
            [['latitude', 'longitude'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'punching_range' => 'Punching Range',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'latitude' => '经度',
            'longitude' => '维度',
            'punching_range' => '打卡范围',
            'work_station' => '小组id',
        ]);
    }




}
