<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\system\base;

use Yii;

/**
 * This is the base-model class for table "member_token".
 *
 * @property string $token
 * @property integer $userid
 * @property string $aliasModel
 */
abstract class MemberToken extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member_token';
    }

     public static function getDb()
    {
        return Yii::$app->get('db');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['token'], 'required'],
            [['userid'], 'integer'],
            [['token'], 'string', 'max' => 50],
            [['userid'], 'unique'],
            [['token'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'token' => 'Token',
            'userid' => 'Userid',
        ];
    }




}
