<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\system\base;

use Yii;

/**
 * This is the base-model class for table "weixin_member".
 *
 * @property string $customer_id
 * @property string $openid
 * @property integer $userid
 * @property string $aliasModel
 */
abstract class WeixinMember extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'weixin_member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid'], 'required'],
            [['userid'], 'integer'],
            [['customer_id', 'openid'], 'string', 'max' => 50],
            [['userid'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'customer_id' => 'Customer ID',
            'openid' => 'Openid',
            'userid' => 'Userid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'customer_id' => '客户ID',
            'openid' => '此客户id下的微信openid',
        ]);
    }




}
