<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_orderby".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $work_station
 * @property integer $shift_index
 * @property integer $schedule_id
 * @property string $aliasModel
 */
abstract class ShiftOrderBy extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_orderby';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'work_station', 'shift_index', 'schedule_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'work_station' => 'Work Station',
            'shift_index' => 'Shift Index',
            'schedule_id' => 'Schedule ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'schedule_id' => '计划id',
        ]);
    }




}
