<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\attendance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_attendance_remind_log".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $create_time
 * @property string $content
 * @property string $aliasModel
 */
abstract class AttendanceRemindLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_attendance_remind_log';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['create_time'], 'safe'],
            [['content'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'create_time' => 'Create Time',
            'content' => 'Content',
        ];
    }




}
