<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\attachment\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_attachment".
 *
 * @property integer $emp_number
 * @property integer $sort_id
 * @property integer $eattach_id
 * @property string $eattach_desc
 * @property string $eattach_filename
 * @property integer $eattach_size
 * @property string $eattach_attachment
 * @property string $eattach_attachment_url
 * @property string $eattach_type
 * @property string $screen
 * @property integer $attached_by
 * @property string $attached_by_name
 * @property string $attached_time
 * @property string $aliasModel
 */
abstract class Attachment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_attachment';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           // [['emp_number', 'eattach_id'], 'required'],
            [['emp_number', 'sort_id', 'eattach_id', 'eattach_size', 'attached_by'], 'integer'],
            [['eattach_attachment'], 'string'],
            [['attached_time'], 'safe'],
            [['eattach_desc', 'eattach_type', 'attached_by_name'], 'string', 'max' => 200],
            [['eattach_filename', 'eattach_attachment_url', 'screen'], 'string', 'max' => 100],
            [['emp_number', 'eattach_id'], 'unique', 'targetAttribute' => ['emp_number', 'eattach_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'emp_number' => 'Emp Number',
            'sort_id' => 'Sort ID',
            'eattach_id' => 'Eattach ID',
            'eattach_desc' => 'Eattach Desc',
            'eattach_filename' => 'Eattach Filename',
            'eattach_size' => 'Eattach Size',
            'eattach_attachment' => 'Eattach Attachment',
            'eattach_attachment_url' => 'Eattach Attachment Url',
            'eattach_type' => 'Eattach Type',
            'screen' => 'Screen',
            'attached_by' => 'Attached By',
            'attached_by_name' => 'Attached By Name',
            'attached_time' => 'Attached Time',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'sort_id' => '关联各个分类表表id 健康  科研 教育',
            'eattach_attachment_url' => '路径',
        ]);
    }




}
