<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_schedule".
 *
 * @property integer $id
 * @property string $name
 * @property string $shift_date
 * @property string $copy_type
 * @property string $status
 * @property string $create_at
 * @property integer $run_java_time
 * @property integer $location_id
 * @property integer $is_confirm
 * @property integer $is_show
 * @property string $roll_name
 *
 * @property \app\models\OhrmWorkShift[] $ohrmWorkShifts
 * @property \app\models\OhrmWorkShiftAssignment[] $ohrmWorkShiftAssignments
 * @property \app\models\OhrmWorkShiftDate[] $ohrmWorkShiftDates
 * @property \app\models\OhrmWorkShiftResult[] $ohrmWorkShiftResults
 * @property \app\models\OhrmWorkShiftType[] $ohrmWorkShiftTypes
 * @property string $aliasModel
 */
abstract class Schedule extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_schedule';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'shift_date', 'copy_type', 'status', 'create_at'], 'required'],
            [['shift_date', 'create_at'], 'safe'],
            [['run_java_time', 'location_id', 'is_confirm', 'is_show'], 'integer'],
            [['name', 'copy_type', 'roll_name'], 'string', 'max' => 250],
            [['status'], 'string', 'max' => 260]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'shift_date' => 'Shift Date',
            'copy_type' => 'Copy Type',
            'status' => 'Status',
            'create_at' => 'Create At',
            'run_java_time' => 'Run Java Time',
            'location_id' => 'Location ID',
            'is_confirm' => 'Is Confirm',
            'is_show' => 'Is Show',
            'roll_name' => 'Roll Name',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'location_id' => '所在小组',
            'is_confirm' => '排班计划表是否确认，1确认，0未确认',
            'roll_name' => '循环新建表的名称',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShifts()
    {
        return $this->hasMany(\app\models\OhrmWorkShift::className(), ['schedule_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShiftAssignments()
    {
        return $this->hasMany(\app\models\OhrmWorkShiftAssignment::className(), ['schedule_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShiftDates()
    {
        return $this->hasMany(\app\models\OhrmWorkShiftDate::className(), ['schedule_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShiftResults()
    {
        return $this->hasMany(\app\models\OhrmWorkShiftResult::className(), ['schedule_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShiftTypes()
    {
        return $this->hasMany(\app\models\OhrmWorkShiftType::className(), ['schedule_id' => 'id']);
    }




}
