<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum_employee".
 *
 * @property string $id
 * @property integer $emp_number
 * @property integer $cur_id
 * @property string $create_time
 * @property string $emp_credit
 * @property string $aliasModel
 */
abstract class CurriculumEmployee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum_employee';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
           /* [['emp_number', 'cur_id'], 'integer'],
            [['create_time'], 'safe'],
            [['emp_credit'], 'string', 'max' => 50]*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
           /* 'id' => 'ID',
            'emp_number' => 'Emp Number',
            'cur_id' => 'Cur ID',
            'create_time' => 'Create Time',
            'emp_credit' => 'Emp Credit',*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'cur_id' => '课程id',
            'create_time' => '创建时间',
            'emp_credit' => '员工考试分数',
        ]);
    }




}
