<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum_answer".
 *
 * @property string $id
 * @property string $question_id
 * @property string $option_answer
 * @property integer $default_answer
 *
 * @property \common\models\curriculum\OhrmCurriculumQuestions $question
 * @property string $aliasModel
 */
abstract class CurriculumAnswer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum_answer';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['question_id'], 'required'],
            [['question_id'], 'integer'],
            [['option_answer'], 'string', 'max' => 250],
            [['default_answer'], 'string', 'max' => 4],
            [['question_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\curriculum\CurriculumQuestions::className(), 'targetAttribute' => ['question_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'question_id' => 'Question ID',
            'option_answer' => 'Option Answer',
            'default_answer' => 'Default Answer',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'question_id' => '考题id',
            'option_answer' => '答案选项',
            'default_answer' => '默认值',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestion()
    {
        return $this->hasOne(\common\models\curriculum\OhrmCurriculumQuestions::className(), ['id' => 'question_id']);
    }




}
