<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum_empanswer".
 *
 * @property string $id
 * @property integer $emp_number
 * @property string $question_id
 * @property string $answer_id
 * @property integer $question_type
 * @property string $cur_id
 * @property string $question_fraction
 * @property integer $cur_emp_id
 * @property string $aliasModel
 */
abstract class CurriculumEmpanswer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum_empanswer';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            /*[['emp_number', 'question_id', 'answer_id', 'cur_id'], 'required'],
            [['emp_number', 'question_id', 'cur_id', 'cur_emp_id'], 'integer'],
            [['answer_id'], 'string'],
            [['question_type'], 'string', 'max' => 2],
            [['question_fraction'], 'string', 'max' => 20]*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'question_id' => 'Question ID',
            'answer_id' => 'Answer ID',
            'question_type' => 'Question Type',
            'cur_id' => 'Cur ID',
            'question_fraction' => 'Question Fraction',
            'cur_emp_id' => 'Cur Emp ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'question_id' => '问题id',
            'answer_id' => '答案',
            'question_type' => '问题类型',
            'cur_id' => '课程id',
            'question_fraction' => '得分',
        ]);
    }




}
