<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum_file".
 *
 * @property string $id
 * @property string $cur_name
 * @property string $cur_url
 * @property string $firstuplod_id
 * @property string $create_time
 * @property integer $cur_id
 * @property string $aliasModel
 */
abstract class CurriculumFile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum_file';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['create_time'], 'safe'],
            [['cur_id'], 'integer'],
            [['cur_name'], 'string', 'max' => 200],
            [['cur_url'], 'string', 'max' => 100],
            [['firstuplod_id'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cur_name' => 'Cur Name',
            'cur_url' => 'Cur Url',
            'firstuplod_id' => 'Firstuplod ID',
            'create_time' => 'Create Time',
            'cur_id' => 'Cur ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'cur_name' => '课程名称',
            'cur_url' => '课程文件路径路径',
            'firstuplod_id' => '第一次上传时的课程id',
            'create_time' => '创建时间',
        ]);
    }




}
