<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\attendance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_attendance_detail".
 *
 * @property integer $id
 * @property integer $record_id
 * @property integer $emp_number
 * @property string $lat
 * @property string $lng
 * @property string $distance
 * @property string $address
 * @property string $create_time
 * @property integer $status
 * @property string $aliasModel
 */
abstract class AttendanceRecordDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_attendance_detail';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['record_id'], 'required'],
            [['record_id', 'emp_number'], 'integer'],
            [['create_time','status'], 'safe'],
            [['lat', 'lng'], 'string', 'max' => 50],
            [['distance'], 'string', 'max' => 10],
            [['address'], 'string', 'max' => 250]
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'record_id' => 'Record ID',
            'emp_number' => 'Emp Number',
            'lat' => 'Lat',
            'lng' => 'Lng',
            'distance' => 'Distance',
            'address' => 'Address',
            'create_time' => 'Create Time',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'lat' => '经度',
            'lng' => '纬度',
            'distance' => '范围',
            'address' => '地址',
            'create_time' => '创建时间',
            'status' => '打卡状态 1上班卡 2中途下班卡 3中途上班卡 4下班卡',
        ]);
    }




}
