<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_pim_city".
 *
 * @property integer $id
 * @property integer $fu_id
 * @property string $name
 * @property integer $type
 * @property string $aliasModel
 */
abstract class City extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_pim_city';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fu_id'], 'integer'],
            [['name'], 'string', 'max' => 30],
            [['type'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fu_id' => 'Fu ID',
            'name' => 'Name',
            'type' => 'Type',
        ];
    }




}
