<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_jiguan".
 *
 * @property string $id
 * @property integer $emp_number
 * @property integer $province
 * @property integer $city
 * @property integer $county
 * @property string $province_name
 * @property string $city_name
 * @property string $county_name
 * @property string $aliasModel
 */
abstract class Jiguan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_jiguan';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'province', 'city', 'county'], 'integer'],
            [['province_name', 'city_name', 'county_name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'province' => 'Province',
            'city' => 'City',
            'county' => 'County',
            'province_name' => 'Province Name',
            'city_name' => 'City Name',
            'county_name' => 'County Name',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'province' => '省',
            'city' => '市',
            'county' => '县',
        ]);
    }




}
