<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_job_title".
 *
 * @property integer $id
 * @property string $job_title
 * @property string $job_description
 * @property string $job_grade
 * @property string $note
 * @property integer $is_deleted
 *
 * @property \common\models\user\HsHrEmployee[] $hsHrEmployees
 * @property \common\models\user\HsHrJobtitEmpstat[] $hsHrJobtitEmpstats
 * @property \common\models\user\OhrmEmploymentStatus[] $estatCodes
 * @property \common\models\user\OhrmJobSpecificationAttachment[] $ohrmJobSpecificationAttachments
 * @property \common\models\user\OhrmJobVacancy[] $ohrmJobVacancies
 * @property string $aliasModel
 */
abstract class Title extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_job_title';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['job_title'], 'required'],
            [['job_title'], 'string', 'max' => 100],
            [['job_description', 'note'], 'string', 'max' => 400],
            [['job_grade'], 'string', 'max' => 50],
            [['is_deleted'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'job_title' => 'Job Title',
            'job_description' => 'Job Description',
            'job_grade' => 'Job Grade',
            'note' => 'Note',
            'is_deleted' => 'Is Deleted',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'job_grade' => '高级中级初级',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmployees()
    {
        return $this->hasMany(\common\models\user\HsHrEmployee::className(), ['job_title_code' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrJobtitEmpstats()
    {
        return $this->hasMany(\common\models\user\HsHrJobtitEmpstat::className(), ['jobtit_code' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstatCodes()
    {
        return $this->hasMany(\common\models\user\OhrmEmploymentStatus::className(), ['id' => 'estat_code'])->viaTable('hs_hr_jobtit_empstat', ['jobtit_code' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobSpecificationAttachments()
    {
        return $this->hasMany(\common\models\user\OhrmJobSpecificationAttachment::className(), ['job_title_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobVacancies()
    {
        return $this->hasMany(\common\models\user\OhrmJobVacancy::className(), ['job_title_code' => 'id']);
    }




}
