<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "work_excel".
 *
 * @property integer $id
 * @property integer $user_name
 * @property string $emp_name
 * @property string $time_in
 * @property string $time_out
 * @property string $tmpclassname
 * @property string $aliasModel
 */
abstract class WorkExcel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work_excel';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_name'], 'integer'],
            [['time_in', 'time_out'], 'safe'],
            [['emp_name', 'tmpclassname'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_name' => 'User Name',
            'emp_name' => 'Emp Name',
            'time_in' => 'Time In',
            'time_out' => 'Time Out',
            'tmpclassname' => 'Tmpclassname',
        ];
    }




}
