<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\healthy\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_healthy_attached".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $year
 * @property integer $is_all_qualified
 * @property string $aliasModel
 */
abstract class HealthyAttached extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_healthy_attached';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
          //  [['emp_number', 'year'], 'integer'],
            //['is_all_qualified'], 'integer', 'max' => 11]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'year' => 'Year',
            //'is_all_qualified' => 'Is All Qualified',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'emp_number' => '员工id',
            'year' => '年份',
            'is_all_qualified' => '是否合格',
        ]);
    }




}
