<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\system\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_user_login_log".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $content
 * @property string $user_name
 * @property string $create_date
 * @property string $aliasModel
 */
abstract class UserLoginLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_user_login_log';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['create_date'], 'safe'],
            [['content'], 'string', 'max' => 255],
            [['user_name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'content' => 'Content',
            'user_name' => 'User Name',
            'create_date' => 'Create Date',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'content' => '错误内容',
        ]);
    }




}
