<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\performance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_bonus_calculation_manage_list".
 *
 * @property integer $id
 * @property string $customerId
 * @property string $bonusDate
 * @property integer $groupId
 * @property integer $status
 * @property integer $emp_number
 * @property string $percent20
 * @property string $percent80
 * @property string $sheetInfo
 * @property string $aliasModel
 */
abstract class BonusCalculationManageList extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_bonus_calculation_manage_list';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bonusDate'], 'safe'],
            [['groupId', 'emp_number','status'], 'integer'],
            [['percent20', 'percent80'], 'number'],
            [['sheetInfo'], 'string'],
            [['customerId'], 'string', 'max' => 20]
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customerId' => 'Customer ID',
            'bonusDate' => 'Bonus Date',
            'groupId' => 'Group ID',
            'status' => 'Status',
            'emp_number' => 'Emp Number',
            'percent20' => 'Percent20',
            'percent80' => 'Percent80',
            'sheetInfo' => 'Sheet Info',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'customerId' => '客户id',
            'bonusDate' => '日期',
            'groupId' => '组id',
            'status' => '状态 0默认10已下发未上报11已下发已上报1确认归档',
            'sheetInfo' => 'excel中行数据',
        ]);
    }




}
