<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\education\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_education_score".
 *
 * @property integer $id
 * @property integer $month
 * @property integer $student_id
 * @property integer $score
 *
 * @property \common\models\Education $student
 * @property string $aliasModel
 */
abstract class EducationScore extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_education_score';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['id'], 'required'],
            [['id', 'month', 'student_id', 'score'], 'integer'],
            //[['id'], 'unique'],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Education::className(), 'targetAttribute' => ['student_id' => 'student_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'month' => 'Month',
            'student_id' => 'Student ID',
            'score' => 'Score',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'month' => '月份',
            'student_id' => '学生',
            'score' => '成绩',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\common\models\education\Education::className(), ['student_id' => 'student_id']);
    }




}
