<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\honor\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_honor".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $status
 * @property string $honor_name
 * @property string $item_name
 * @property string $ranking
 * @property string $done_unit
 * @property string $grant_award
 * @property string $reward
 * @property string $reward_class
 * @property string $reward_type
 * @property string $reward_number
 * @property string $reward_time
 * @property string $remark
 * @property string $aliasModel
 */
abstract class Emphonor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_honor';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['emp_number', 'reward_time'], 'required'],
            [['emp_number'], 'integer'],
           // [['reward_number'], 'string'],
            [['reward_time'], 'safe'],
            [['status', 'done_unit', 'grant_award', 'reward', 'reward_class', 'reward_type', 'remark'], 'string', 'max' => 255],
            [['honor_name', 'item_name', 'ranking'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'status' => 'Status',
            'honor_name' => 'Honor Name',
            'item_name' => 'Item Name',
            'ranking' => 'Ranking',
            'done_unit' => 'Done Unit',
            'grant_award' => 'Grant Award',
            'reward' => 'Reward',
            'reward_class' => 'Reward Class',
            'reward_type' => 'Reward Type',
            'reward_number' => 'Reward Number',
            'reward_time' => 'Reward Time',
            'remark' => 'Remark',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'status' => '0报奖   1获奖',
            'honor_name' => '获奖名称',
            'item_name' => '项目名称',
            'ranking' => '排名 M/N',
            'done_unit' => '完成单位',
            'grant_award' => '颁奖单位',
            'reward' => '奖励',
            'reward_class' => '奖励类别',
            'reward_type' => '奖励种类',
            'reward_number' => '奖项编号',
            'reward_time' => '报奖获奖时间',
            'remark' => '备注',
        ]);
    }




}
