<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\group\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_group_menus".
 *
 * @property integer $id
 * @property string $name
 * @property string $m
 * @property string $c
 * @property string $act
 * @property integer $parentid
 * @property integer $level
 * @property integer $sort
 * @property integer $display
 * @property string $aliasModel
 */
abstract class GroupMenus extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_group_menus';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parentid', 'level', 'sort'], 'integer'],
            [['name'], 'string', 'max' => 125],
            [['m', 'c', 'act'], 'string', 'max' => 32],
            [['display'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'm' => 'M',
            'c' => 'C',
            'act' => 'Act',
            'parentid' => 'Parentid',
            'level' => 'Level',
            'sort' => 'Sort',
            'display' => 'Display',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => 'id',
            'name' => '菜单名称',
            'm' => '模块名',
            'c' => '控制器名',
            'act' => '方法名',
            'parentid' => '父级菜单id',
            'level' => '等级',
            'sort' => '排序字段',
            'display' => '是否显示',
        ]);
    }




}
