<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\performance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_performance_param".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $year
 * @property string $month
 * @property string $type
 * @property string $status
 * @property string $aliasModel
 */
abstract class PerformanceParam extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_performance_param';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['year', 'month', 'type', 'status','subunit'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'year' => 'Year',
            'month' => 'Month',
            'type' => 'Type',
            'status' => 'Status',
            'subunit' => 'Subunit',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'user_id' => '用户id',
            'year' => '选中的年份',
            'month' => '选中的月份',
            'type' => '选中的类型 1月度 2年度',
            'status' => '选中的状态 1未下发 2已下发未上报 3已下发已上报 4确认归档',
        ]);
    }




}
