<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\leave\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_leave_comment".
 *
 * @property integer $id
 * @property integer $leave_id
 * @property string $created
 * @property string $created_by_name
 * @property integer $created_by_id
 * @property integer $created_by_emp_number
 * @property string $comments
 *
 * @property \common\models\leave\OhrmLeave $leave
 * @property \common\models\leave\OhrmUser $createdBy
 * @property \common\models\leave\HsHrEmployee $createdByEmpNumber
 * @property string $aliasModel
 */
abstract class LeaveComment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_leave_comment';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['leave_id', 'created_by_name'], 'required'],
            [['leave_id', 'created_by_id', 'created_by_emp_number'], 'integer'],
            [['created'], 'safe'],
            [['created_by_name', 'comments'], 'string', 'max' => 255],
            [['leave_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\leave\Leave::className(), 'targetAttribute' => ['leave_id' => 'id']],
            [['created_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\user\User::className(), 'targetAttribute' => ['created_by_id' => 'id']],
            [['created_by_emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\Employee::className(), 'targetAttribute' => ['created_by_emp_number' => 'emp_number']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'leave_id' => 'Leave ID',
            'created' => 'Created',
            'created_by_name' => 'Created By Name',
            'created_by_id' => 'Created By ID',
            'created_by_emp_number' => 'Created By Emp Number',
            'comments' => 'Comments',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeave()
    {
        return $this->hasOne(\common\models\leave\Leave::className(), ['id' => 'leave_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\user\User::className(), ['id' => 'created_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedByEmpNumber()
    {
        return $this->hasOne(\common\models\employee\Employee::className(), ['emp_number' => 'created_by_emp_number']);
    }




}
