<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\Journal\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_journal".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $journal_name
 * @property string $job
 * @property string $start_time
 * @property string $remark
 * @property string $aliasModel
 */
abstract class Journal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_journal';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['start_time'], 'safe'],
            [['journal_name', 'job'], 'string', 'max' => 100],
            [['remark'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'journal_name' => 'Journal Name',
            'job' => 'Job',
            'start_time' => 'Start Time',
            'remark' => 'Remark',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'journal_name' => '杂志名',
            'job' => '职务',
            'start_time' => '聘任时间',
            'remark' => '备注',
        ]);
    }




}
