<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\leave\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_leave_leave_entitlement".
 *
 * @property integer $id
 * @property integer $leave_id
 * @property integer $entitlement_id
 * @property string $length_days
 *
 * @property \common\models\OhrmLeaveEntitlement $entitlement
 * @property \common\models\OhrmLeave $leave
 * @property string $aliasModel
 */
abstract class LeaveLeaveEntitlement extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_leave_leave_entitlement';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['leave_id', 'entitlement_id'], 'required'],
            [['leave_id', 'entitlement_id'], 'integer'],
            [['length_days'], 'number'],
            [['entitlement_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\leave\LeaveEntitlement::className(), 'targetAttribute' => ['entitlement_id' => 'id']],
            [['leave_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\leave\Leave::className(), 'targetAttribute' => ['leave_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'leave_id' => 'Leave ID',
            'entitlement_id' => 'Entitlement ID',
            'length_days' => 'Length Days',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntitlement()
    {
        return $this->hasOne(\common\models\leave\LeaveEntitlement::className(), ['id' => 'entitlement_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeave()
    {
        return $this->hasOne(\common\models\leave\Leave::className(), ['id' => 'leave_id']);
    }




}
