<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\overtime\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_leave".
 *
 * @property integer $id
 * @property string $date
 * @property string $length_hours
 * @property string $length_days
 * @property integer $status
 * @property string $comments
 * @property string $leave_request_id
 * @property string $leave_type_id
 * @property integer $emp_number
 * @property string $start_time
 * @property string $end_time
 * @property integer $duration_type
 * @property integer $is_pro
 *
 * @property \common\models\overtime\OhrmLeaveRequest $leaveRequest
 * @property \common\models\overtime\OhrmLeaveType $leaveType
 * @property \common\models\overtime\OhrmLeaveComment[] $ohrmLeaveComments
 * @property \common\models\overtime\OhrmLeaveLeaveEntitlement[] $ohrmLeaveLeaveEntitlements
 * @property string $aliasModel
 */
abstract class Leave extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_leave';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'start_time', 'end_time'], 'safe'],
            [['length_hours', 'length_days'], 'number'],
            [['status', 'leave_request_id', 'leave_type_id', 'emp_number'], 'integer'],
            [['leave_request_id', 'leave_type_id', 'emp_number'], 'required'],
            [['comments'], 'string', 'max' => 256],
            [['duration_type', 'is_pro'], 'string', 'max' => 4],
            [['leave_request_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\overtime\OhrmLeaveRequest::className(), 'targetAttribute' => ['leave_request_id' => 'id']],
            [['leave_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\overtime\OhrmLeaveType::className(), 'targetAttribute' => ['leave_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'length_hours' => 'Length Hours',
            'length_days' => 'Length Days',
            'status' => 'Status',
            'comments' => 'Comments',
            'leave_request_id' => 'Leave Request ID',
            'leave_type_id' => 'Leave Type ID',
            'emp_number' => 'Emp Number',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'duration_type' => 'Duration Type',
            'is_pro' => 'Is Pro',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'duration_type' => '0：1天；1上午；2下午',
            'is_pro' => '是否已经审核 1是',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaveRequest()
    {
        return $this->hasOne(\common\models\overtime\OhrmLeaveRequest::className(), ['id' => 'leave_request_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaveType()
    {
        return $this->hasOne(\common\models\overtime\OhrmLeaveType::className(), ['id' => 'leave_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveComments()
    {
        return $this->hasMany(\common\models\overtime\OhrmLeaveComment::className(), ['leave_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveLeaveEntitlements()
    {
        return $this->hasMany(\common\models\overtime\OhrmLeaveLeaveEntitlement::className(), ['leave_id' => 'id']);
    }




}
