<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\overtime\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_type".
 *
 * @property integer $id
 * @property string $create_at
 * @property integer $schedule_id
 * @property string $name
 * @property string $start_time
 * @property string $end_time
 * @property string $skill_id
 * @property string $status
 * @property integer $copy_type
 * @property integer $require_employee
 * @property integer $is_grant
 * @property integer $is_night_shift
 * @property double $duty_factor
 * @property integer $is_amont_work
 * @property integer $location_id
 * @property string $week_select
 * @property string $start_time_afternoon
 * @property string $end_time_afternoon
 * @property integer $is_work_overtime
 * @property integer $is_work_half
 * @property integer $clock_in
 * @property integer $is_daka_half
 * @property string $remark
 * @property integer $is_approval
 * @property string $color
 *
 * @property \common\models\overtime\OhrmWorkShift[] $ohrmWorkShifts
 * @property \common\models\overtime\OhrmWorkSchedule $schedule
 * @property \common\models\overtime\OhrmWorkTypeSkill[] $ohrmWorkTypeSkills
 * @property string $aliasModel
 */
abstract class ShiftType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_type';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['create_at'], 'required'],
            [['create_at', 'start_time', 'end_time', 'start_time_afternoon', 'end_time_afternoon'], 'safe'],
            [['schedule_id', 'copy_type', 'require_employee', 'location_id', 'is_work_overtime', 'is_work_half', 'clock_in', 'is_approval'], 'integer'],
            [['duty_factor'], 'number'],
            [['name', 'status'], 'string', 'max' => 250],
            [['skill_id', 'week_select', 'remark', 'color'], 'string', 'max' => 255],
            [['is_grant', 'is_night_shift', 'is_amont_work', 'is_daka_half'], 'string', 'max' => 4],
            [['schedule_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\overtime\OhrmWorkSchedule::className(), 'targetAttribute' => ['schedule_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'create_at' => 'Create At',
            'schedule_id' => 'Schedule ID',
            'name' => 'Name',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'skill_id' => 'Skill ID',
            'status' => 'Status',
            'copy_type' => 'Copy Type',
            'require_employee' => 'Require Employee',
            'is_grant' => 'Is Grant',
            'is_night_shift' => 'Is Night Shift',
            'duty_factor' => 'Duty Factor',
            'is_amont_work' => 'Is Amont Work',
            'location_id' => 'Location ID',
            'week_select' => 'Week Select',
            'start_time_afternoon' => 'Start Time Afternoon',
            'end_time_afternoon' => 'End Time Afternoon',
            'is_work_overtime' => 'Is Work Overtime',
            'is_work_half' => 'Is Work Half',
            'clock_in' => 'Clock In',
            'is_daka_half' => 'Is Daka Half',
            'remark' => 'Remark',
            'is_approval' => 'Is Approval',
            'color' => 'Color',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => '排班类型名',
            'skill_id' => '岗位所需要技能',
            'is_grant' => '是否需要补助金 1是 0 否',
            'is_night_shift' => '是否夜班 1是 0 否',
            'duty_factor' => '工作系数',
            'is_amont_work' => '是否添加工作量 1添加 0不添加',
            'location_id' => '部门ID',
            'week_select' => '自定义周几排班',
            'start_time_afternoon' => ' 中途上班打卡',
            'end_time_afternoon' => '中途下班时间',
            'is_work_overtime' => '是否是加班类型的班次1是，0不是',
            'is_work_half' => '是否是只上上午半天班',
            'clock_in' => '是否可以早退，0可以，1不可以',
            'is_daka_half' => '是否 中途打卡  1是  0否',
            'remark' => '班次备注',
            'is_approval' => '班次是否需要审批，0不需要，1需要审批',
            'color' => '班次默认颜色',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShifts()
    {
        return $this->hasMany(\common\models\overtime\OhrmWorkShift::className(), ['shift_type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedule()
    {
        return $this->hasOne(\common\models\overtime\OhrmWorkSchedule::className(), ['id' => 'schedule_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkTypeSkills()
    {
        return $this->hasMany(\common\models\overtime\OhrmWorkTypeSkill::className(), ['shift_type_id' => 'id']);
    }




}
