<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\overtime\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_result".
 *
 * @property integer $id
 * @property integer $schedule_id
 * @property integer $emp_number
 * @property integer $shift_type_id
 * @property string $shift_date
 * @property string $shift_type_name
 * @property integer $leave_type
 * @property integer $rest_type
 * @property integer $leave_type_id
 *
 * @property \common\models\overtime\OhrmWorkSchedule $schedule
 * @property string $aliasModel
 */
abstract class ShiftResult extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_result';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['schedule_id', 'shift_date'], 'required'],
            [['schedule_id', 'emp_number', 'shift_type_id', 'leave_type', 'rest_type', 'leave_type_id'], 'integer'],
            [['shift_date'], 'safe'],
            [['shift_type_name'], 'string', 'max' => 255],
            [['schedule_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\overtime\OhrmWorkSchedule::className(), 'targetAttribute' => ['schedule_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'schedule_id' => 'Schedule ID',
            'emp_number' => 'Emp Number',
            'shift_type_id' => 'Shift Type ID',
            'shift_date' => 'Shift Date',
            'shift_type_name' => 'Shift Type Name',
            'leave_type' => 'Leave Type',
            'rest_type' => 'Rest Type',
            'leave_type_id' => 'Leave Type ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'shift_type_id' => '排班类型',
            'leave_type' => ' 0，没有假期，1全天假，2半天假',
            'rest_type' => '休息类型，1休全天，2休息半天',
            'leave_type_id' => '假期类型id',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedule()
    {
        return $this->hasOne(\common\models\overtime\OhrmWorkSchedule::className(), ['id' => 'schedule_id']);
    }




}
