<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\reward\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_reward".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $is_reward
 * @property string $explain
 * @property string $result
 * @property string $aliasModel
 */
abstract class Reward extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_reward';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['is_reward'], 'string', 'max' => 4],
            [['info', 'result'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'is_reward' => 'Is Reward',
            'info' => 'Info',
            'result' => 'Result',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'is_reward' => '1:奖励  2：惩罚',
            'info' => '说明',
            'result' => '结果',
        ]);
    }




}
