<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_result_confirm".
 *
 * @property integer $id
 * @property integer $schedule_id
 * @property integer $emp_number
 * @property integer $shift_type_id
 * @property string $shift_date
 * @property string $shift_type_name
 * @property integer $leave_type
 * @property integer $rest_type
 * @property string $aliasModel
 */
abstract class ShiftResultConfirm extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_result_confirm';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['schedule_id', 'shift_date'], 'required'],
            [['schedule_id', 'emp_number', 'shift_type_id','shift_type_id_backup', 'leave_type', 'rest_type','frist_type_id','second_type_id','third_type_id'], 'integer'],
            [['shift_date'], 'safe'],
            [['shift_type_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'schedule_id' => 'Schedule ID',
            'emp_number' => 'Emp Number',
            'shift_type_id' => 'Shift Type ID',
            'shift_date' => 'Shift Date',
            'shift_type_name' => 'Shift Type Name',
            'leave_type' => 'Leave Type',
            'rest_type' => 'Rest Type',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'shift_type_id' => '排班类型',
            'leave_type' => ' 0，没有假期，1全天假，2半天假',
            'rest_type' => '休息类型，1休全天，2休息半天',
        ]);
    }




}
