<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
/**
 * This is the base-model class for table "ohrm_user".
 *
 * @property integer $id
 * @property integer $user_role_id
 * @property integer $emp_number
 * @property string $user_name
 * @property string $user_password
 * @property integer $deleted
 * @property integer $status
 * @property string $date_entered
 * @property string $date_modified
 * @property integer $modified_user_id
 * @property integer $created_by
 *
 * @property \common\models\HsHrMailnotifications[] $hsHrMailnotifications
 * @property \common\models\OhrmLeaveAdjustment[] $ohrmLeaveAdjustments
 * @property \common\models\OhrmLeaveComment[] $ohrmLeaveComments
 * @property \common\models\OhrmLeaveEntitlement[] $ohrmLeaveEntitlements
 * @property \common\models\OhrmLeaveRequestComment[] $ohrmLeaveRequestComments
 * @property \common\models\OhrmOpenidUserIdentity[] $ohrmOpenidUserIdentities
 * @property \common\models\OhrmPerformanceTrackerLog[] $ohrmPerformanceTrackerLogs
 * @property \common\models\OhrmTimesheetActionLog[] $ohrmTimesheetActionLogs
 * @property \common\models\HsHrEmployee $empNumber
 * @property \common\models\OhrmUserRole $userRole
 * @property \common\models\OhrmUserNotify[] $ohrmUserNotifies
 * @property \common\models\OhrmUserNotifyList[] $ohrmUserNotifyLists
 * @property \common\models\OhrmUserNotifySubscription[] $ohrmUserNotifySubscriptions
 * @property string $aliasModel
 */
abstract class SystemUsers extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_user';
    }
    public static function getDb(){
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_role_id'], 'false'],
            [['user_role_id', 'emp_number', 'modified_user_id'], 'integer'],
            [['date_entered', 'date_modified'], 'safe'],
            [['user_name'], 'string', 'max' => 40],
            [['user_password'], 'string', 'max' => 255],
            [['deleted', 'status'], 'string', 'max' => 1],
            [['user_name'], 'unique'],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']],
            [['user_role_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SystemUserRole::className(), 'targetAttribute' => ['user_role_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_role_id' => 'User Role ID',
            'emp_number' => 'Emp Number',
            'user_name' => 'User Name',
            'user_password' => 'User Password',
            'deleted' => 'Deleted',
            'status' => 'Status',
            'date_entered' => 'Date Entered',
            'date_modified' => 'Date Modified',
            'modified_user_id' => 'Modified User ID',
            'created_by' => 'Created By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrMailnotifications()
    {
        return $this->hasMany(\common\models\HsHrMailnotifications::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveAdjustments()
    {
        return $this->hasMany(\common\models\OhrmLeaveAdjustment::className(), ['created_by_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveComments()
    {
        return $this->hasMany(\common\models\OhrmLeaveComment::className(), ['created_by_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveEntitlements()
    {
        return $this->hasMany(\common\models\OhrmLeaveEntitlement::className(), ['created_by_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveRequestComments()
    {
        return $this->hasMany(\common\models\OhrmLeaveRequestComment::className(), ['created_by_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmOpenidUserIdentities()
    {
        return $this->hasMany(\common\models\OhrmOpenidUserIdentity::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceTrackerLogs()
    {
        return $this->hasMany(\common\models\OhrmPerformanceTrackerLog::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmTimesheetActionLogs()
    {
        return $this->hasMany(\common\models\OhrmTimesheetActionLog::className(), ['performed_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(\common\models\Employee::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSystemUserRole()
    {
        return $this->hasOne(\common\models\SystemUserRole::className(), ['id' => 'user_role_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmUserNotifies()
    {
        return $this->hasMany(\common\models\OhrmUserNotify::className(), ['sender' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmUserNotifyLists()
    {
        return $this->hasMany(\common\models\OhrmUserNotifyList::className(), ['receiver_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmUserNotifySubscriptions()
    {
        return $this->hasMany(\common\models\OhrmUserNotifySubscription::className(), ['user' => 'id']);
    }




}
