<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "emp_excel".
 *
 * @property integer $id
 * @property string $user_name
 * @property string $job_title_code
 * @property string $job_title_time
 * @property string $keyan_title_code
 * @property string $keyan_title_time
 * @property string $teacher_title_code
 * @property string $teacher_title_time
 * @property string $tutor
 * @property string $aliasModel
 */
abstract class Empexcel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'emp_excel';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_name', 'job_title_code', 'keyan_title_code', 'teacher_title_code', 'tutor'], 'string', 'max' => 255],
            [['job_title_time', 'keyan_title_time', 'teacher_title_time'], 'string', 'max' => 111]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_name' => 'User Name',
            'job_title_code' => 'Job Title Code',
            'job_title_time' => 'Job Title Time',
            'keyan_title_code' => 'Keyan Title Code',
            'keyan_title_time' => 'Keyan Title Time',
            'teacher_title_code' => 'Teacher Title Code',
            'teacher_title_time' => 'Teacher Title Time',
            'tutor' => 'Tutor',
        ];
    }




}
