<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum".
 *
 * @property string $id
 * @property string $name
 * @property integer $is_start
 * @property integer $cu_type
 * @property string $trainer
 * @property string $credit
 * @property string $pass_score
 * @property string $interval_jian
 * @property string $answer_time
 * @property string $stat_time
 * @property string $end_time
 * @property string $cu_describe
 * @property integer $file_id
 * @property string $videourl
 * @property string $create_time
 * @property integer $work_station
 *
 * @property \common\models\curriculum\OhrmCurriculumProblems[] $ohrmCurriculumProblems
 * @property string $aliasModel
 */
abstract class Curriculum extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['stat_time', 'end_time', 'create_time'], 'safe'],
            [['file_id', 'work_station'], 'integer'],
            [['name', 'videourl'], 'string', 'max' => 200],
            [['is_start', 'cu_type'], 'integer'],
            [['trainer'], 'string', 'max' => 100],
            [['credit', 'pass_score', 'interval_jian', 'answer_time'], 'string', 'max' => 20],
            [['cu_describe'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'is_start' => 'Is Start',
            'cu_type' => 'Cu Type',
            'trainer' => 'Trainer',
            'credit' => 'Credit',
            'pass_score' => 'Pass Score',
            'interval_jian' => 'Interval Jian',
            'answer_time' => 'Answer Time',
            'stat_time' => 'Stat Time',
            'end_time' => 'End Time',
            'cu_describe' => 'Cu Describe',
            'file_id' => 'File ID',
            'videourl' => 'Videourl',
            'create_time' => 'Create Time',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => '课程名称',
            'is_start' => '是否开始考试',
            'cu_type' => '课程类型 1选修 2必修 3其他',
            'trainer' => '培训讲师',
            'credit' => '课程学分',
            'pass_score' => '及格分数线',
            'interval_jian' => '考试间隔',
            'answer_time' => '答题时间',
            'stat_time' => '开始时间',
            'end_time' => '结束时间',
            'cu_describe' => '描述',
            'file_id' => '文件表id',
            'videourl' => '网络视频链接',
            'create_time' => '创建时间',
            'work_station' => '组ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmCurriculumProblems()
    {
        return $this->hasMany(\common\models\curriculum\OhrmCurriculumProblems::className(), ['curriculum_id' => 'id']);
    }




}
