<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_schedule_constraint".
 *
 * @property integer $id
 * @property string $description
 * @property integer $work_station
 * @property string $contranct
 * @property string $aliasModel
 */
abstract class Constraint extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_schedule_constraint';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['work_station'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['contranct'], 'string', 'max' => 5000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'work_station' => 'Work Station',
            'contranct' => 'Contranct',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'work_station' => '约束所属部门',
            'contranct' => '约束条件',
        ]);
    }




}
