<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\thesis\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_thesis_publication".
 *
 * @property integer $id
 * @property string $publication_type
 * @property string $aliasModel
 */
abstract class Publication extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_thesis_publication';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['publication_type'], 'required'],
            [['publication_type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'publication_type' => 'Publication Type',
        ];
    }




}
