<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\teach\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_teach".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $school
 * @property string $major
 * @property integer $record_id
 * @property integer $degree_id
 * @property integer $school_type
 * @property string $start_time
 * @property string $end_time
 * @property string $remarks
 * @property string $aliasModel
 */
abstract class Teach extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_teach';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['start_time', 'end_time'], 'safe'],
            [['remarks'], 'string'],
            [['school', 'major'], 'string', 'max' => 255],
            [['record_id', 'degree_id', 'school_type'], 'string', 'max' => 4]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'school' => 'School',
            'major' => 'Major',
            'record_id' => 'Record ID',
            'degree_id' => 'Degree ID',
            'school_type' => 'School Type',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'remarks' => 'Remarks',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'emp_number' => '员工id',
            'school' => '学校',
            'major' => '专业',
            'record_id' => '学历_id',
            'degree_id' => '学位_id',
            'school_type' => '学校类型   1：全日制  2：在职',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'remarks' => '备注',
        ]);
    }

    public function getDegree()
    {
        return $this->hasMany(\common\models\teach\Degree::className(), ['id' => 'degree_id']);
    }

    public function getEducation()
    {
        return $this->hasMany(\common\models\teach\Education::className(), ['id' => 'record_id']);
    }



}
