<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\folder\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_file".
 *
 * @property integer $id
 * @property string $file_name
 * @property integer $file_size
 * @property integer $folder_class
 * @property string $file_time
 * @property string $aliasModel
 */
abstract class File extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_file';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
          /*  [['file_size'], 'string'],
            [['file_time'], 'safe'],
            [['file_name'], 'string', 'max' => 255]*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file_name' => 'File Name',
            'file_size' => 'File Size',
            'file_time' => 'File Time',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'file_name' => '文件名称',
            'file_size' => '文件大小',
            'file_time' => '创建时间',
        ]);
    }




}
