<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\employee\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_emp_education".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $education_id
 * @property string $institute
 * @property string $major
 * @property string $year
 * @property string $score
 * @property string $start_date
 * @property string $end_date
 *
 * @property \common\models\employee\HsHrEmployee $empNumber
 * @property \common\models\employee\OhrmEducation $education
 * @property string $aliasModel
 */
abstract class EmpEducation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_emp_education';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'education_id'], 'required'],
            [['emp_number', 'education_id'], 'integer'],
            [['year'], 'number'],
            [['start_date', 'end_date'], 'safe'],
            [['institute', 'major'], 'string', 'max' => 100],
            [['score'], 'string', 'max' => 25],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\HsHrEmployee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']],
            [['education_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\OhrmEducation::className(), 'targetAttribute' => ['education_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'education_id' => 'Education ID',
            'institute' => 'Institute',
            'major' => 'Major',
            'year' => 'Year',
            'score' => 'Score',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\employee\HsHrEmployee::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducation()
    {
        return $this->hasOne(\common\models\employee\OhrmEducation::className(), ['id' => 'education_id']);
    }




}
