<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_date".
 *
 * @property integer $id
 * @property string $shift_date
 * @property integer $schedule_id
 * @property integer $work_station
 *
 * @property \common\models\OhrmWorkSchedule $schedule
 * @property string $aliasModel
 */
abstract class ShiftDate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_date';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shift_date', 'schedule_id'], 'required'],
            [['shift_date'], 'safe'],
            [['schedule_id', 'work_station'], 'integer'],
            [['schedule_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\Schedule::className(), 'targetAttribute' => ['schedule_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shift_date' => 'Shift Date',
            'schedule_id' => 'Schedule ID',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'work_station' => '所属小组',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedule()
    {
        return $this->hasOne(\common\models\shift\Schedule::className(), ['id' => 'schedule_id']);
    }

    public function getShift()
    {
        return $this->hasMany(\common\models\shift\Shift::className(), ['shiftdate_id' => 'id']);
    }




}
