<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_education_type".
 *
 * @property integer $id
 * @property string $type
 *
 * @property \common\models\HsHrEducation[] $hsHrEducations
 * @property string $aliasModel
 */
abstract class EducationType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_education_type';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
            [['type'], 'string', 'max' => 100],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'type' => '教育 人员类别',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEducations()
    {
        return $this->hasMany(\common\models\HsHrEducation::className(), ['type_id' => 'id']);
    }




}
