<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_subunit".
 *
 * @property integer $id
 * @property string $name
 * @property string $unit_id
 * @property string $description
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property integer $leader_id
 * @property integer $is_link_leave
 *
 * @property \common\models\HsHrEmployee[] $hsHrEmployees
 * @property string $aliasModel
 */
abstract class Subunit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_subunit';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['lft', 'rgt', 'level', 'leader_id'], 'integer'],
            [['name', 'unit_id'], 'string', 'max' => 100],
            [['description'], 'string', 'max' => 400],
            [['is_link_leave'], 'string', 'max' => 1],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'unit_id' => 'Unit ID',
            'description' => 'Description',
            'lft' => 'Lft',
            'rgt' => 'Rgt',
            'level' => 'Level',
            'leader_id' => 'Leader ID',
            'is_link_leave' => 'Is Link Leave',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'leader_id' => '组长id',
            'is_link_leave' => '是否关联假期（仅限组员间调班申请审批场景）
0 不关联  1关联',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmployees()
    {
        return $this->hasMany(\common\models\Employee::className(), ['work_station' => 'id']);
    }




}
