<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\performance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_bonus_calculation_manage_config".
 *
 * @property integer $id
 * @property string $customerId
 * @property integer $groupId
 * @property string $userField
 * @property string $checkingField
 * @property string $userGroup
 * @property string $aliasModel
 */
abstract class BonusCalculationManageConfig extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_bonus_calculation_manage_config';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customerId'], 'string', 'max' => 20],
            [['groupId'], 'integer', 'max' => 4],
            [['userField', 'checkingField'], 'string', 'max' => 500],
            [['userGroup'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customerId' => 'Customer ID',
            'groupId' => 'Group ID',
            'userField' => 'User Field',
            'checkingField' => 'Checking Field',
            'userGroup' => 'User Group',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'customerId' => '客户id',
            'groupId' => '顶级组id',
            'userField' => '工资号列',
            'checkingField' => '需要校验的列名称',
            'userGroup' => '设置人员所属组',
        ]);
    }




}
