<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_emp_termination_reason".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\user\OhrmEmpTermination[] $ohrmEmpTerminations
 * @property string $aliasModel
 */
abstract class Reason extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_emp_termination_reason';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmpTerminations()
    {
        return $this->hasMany(\common\models\user\OhrmEmpTermination::className(), ['reason_id' => 'id']);
    }




}
