<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\folder\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_folder".
 *
 * @property integer $id
 * @property string $folder_name
 * @property integer $folder_class
 * @property string $time
 * @property string $aliasModel
 */
abstract class Folder extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_folder';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['time'], 'safe'],
            [['folder_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'folder_name' => 'Folder Name',
            'time' => 'Time',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'folder_name' => '文件夹名',
            'time' => '创建时间',
        ]);
    }




}
