<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "config_customer".
 *
 * @property integer $id
 * @property string $domin
 * @property string $customer_name
 * @property integer $status
 * @property string $aliasModel
 */
abstract class ConfigCustomer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'config_customer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status'], 'integer'],
            [['domin', 'customer_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'domin' => 'Domin',
            'customer_name' => 'Customer Name',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'domin' => '域名',
            'customer_name' => '客户名称',
            'status' => '状态；1开启，0 关闭',
        ]);
    }




}
