<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_picture".
 *
 * @property integer $emp_number
 * @property string $epic_picture_url
 * @property string $epic_picture
 * @property string $epic_filename
 * @property string $epic_type
 * @property string $epic_file_size
 * @property string $epic_file_width
 * @property string $epic_file_height
 *
 * @property \common\models\HsHrEmployee $empNumber
 * @property string $aliasModel
 */
abstract class EmpPicture extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_picture';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'required'],
            [['emp_number'], 'integer'],
            [['epic_picture'], 'string'],
            [['epic_picture_url', 'epic_filename'], 'string', 'max' => 100],
            [['epic_type'], 'string', 'max' => 50],
            [['epic_file_size', 'epic_file_width', 'epic_file_height'], 'string', 'max' => 20],
            [['emp_number'], 'unique'],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'emp_number' => 'Emp Number',
            'epic_picture_url' => 'Epic Picture Url',
            'epic_picture' => 'Epic Picture',
            'epic_filename' => 'Epic Filename',
            'epic_type' => 'Epic Type',
            'epic_file_size' => 'Epic File Size',
            'epic_file_width' => 'Epic File Width',
            'epic_file_height' => 'Epic File Height',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'epic_picture_url' => '图片路径',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\Employee::className(), ['emp_number' => 'emp_number']);
    }




}
