<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_leave_entitlement".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $no_of_days
 * @property string $days_used
 * @property integer $leave_type_id
 * @property string $from_date
 * @property string $to_date
 * @property string $credited_date
 * @property string $note
 * @property integer $entitlement_type
 * @property integer $deleted
 * @property integer $created_by_id
 * @property string $created_by_name
 *
 * @property \common\models\OhrmLeaveType $leaveType
 * @property \common\models\HsHrEmployee $empNumber
 * @property \common\models\OhrmLeaveEntitlementType $entitlementType
 * @property \common\models\OhrmUser $createdBy
 * @property \common\models\OhrmLeaveEntitlementAdjustment[] $ohrmLeaveEntitlementAdjustments
 * @property \common\models\OhrmLeaveLeaveEntitlement[] $ohrmLeaveLeaveEntitlements
 * @property string $aliasModel
 */
abstract class LeaveEntitlement extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_leave_entitlement';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'no_of_days', 'leave_type_id', 'from_date', 'entitlement_type'], 'required'],
            [['emp_number', 'leave_type_id', 'entitlement_type', 'created_by_id'], 'integer'],
            [['no_of_days', 'days_used'], 'number'],
            [['from_date', 'to_date', 'credited_date'], 'safe'],
            [['note', 'created_by_name'], 'string', 'max' => 255],
            [['leave_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LeaveType::className(), 'targetAttribute' => ['leave_type_id' => 'id']],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']],
            //[['entitlement_type'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LeaveEntitlementType::className(), 'targetAttribute' => ['entitlement_type' => 'id']],
            [['created_by_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SystemUsers::className(), 'targetAttribute' => ['created_by_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'no_of_days' => 'No Of Days',
            'days_used' => 'Days Used',
            'leave_type_id' => 'Leave Type ID',
            'from_date' => 'From Date',
            'to_date' => 'To Date',
            'credited_date' => 'Credited Date',
            'note' => 'Note',
            'entitlement_type' => 'Entitlement Type',
            'deleted' => 'Deleted',
            'created_by_id' => 'Created By ID',
            'created_by_name' => 'Created By Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaveType()
    {
        return $this->hasOne(\common\models\LeaveType::className(), ['id' => 'leave_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\Employee::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntitlementType()
    {
        return $this->hasOne(\common\models\LeaveEntitlementType::className(), ['id' => 'entitlement_type']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\common\models\SystemUsers::className(), ['id' => 'created_by_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveEntitlementAdjustments()
    {
        return $this->hasMany(\common\models\LeaveEntitlementAdjustment::className(), ['entitlement_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveLeaveEntitlements()
    {
        return $this->hasMany(\common\models\LeaveLeaveEntitlement::className(), ['entitlement_id' => 'id']);
    }




}
