<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_leave_request".
 *
 * @property integer $id
 * @property integer $leave_type_id
 * @property string $date_applied
 * @property integer $emp_number
 * @property string $comments
 * @property integer $is_pro
 * @property string $create_time
 *
 * @property \common\models\OhrmLeave[] $ohrmLeaves
 * @property \common\models\HsHrEmployee $empNumber
 * @property \common\models\OhrmLeaveType $leaveType
 * @property \common\models\OhrmLeaveRequestComment[] $ohrmLeaveRequestComments
 * @property string $aliasModel
 */
abstract class LeaveRequest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_leave_request';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['leave_type_id', 'date_applied', 'emp_number'], 'required'],
            [['leave_type_id', 'emp_number'], 'integer'],
            [['date_applied', 'create_time'], 'safe'],
            [['comments'], 'string', 'max' => 256],
            [['is_pro'], 'string', 'max' => 4],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']],
            [['leave_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\LeaveType::className(), 'targetAttribute' => ['leave_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'leave_type_id' => 'Leave Type ID',
            'date_applied' => 'Date Applied',
            'emp_number' => 'Emp Number',
            'comments' => 'Comments',
            'is_pro' => 'Is Pro',
            'create_time' => 'Create Time',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'is_pro' => '是否已审核 1是',
            'create_time' => '创建时间',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaves()
    {
        return $this->hasMany(\common\models\Leave::className(), ['leave_request_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\Employee::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaveType()
    {
        return $this->hasOne(\common\models\LeaveType::className(), ['id' => 'leave_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveRequestComments()
    {
        return $this->hasMany(\common\models\LeaveRequestComment::className(), ['leave_request_id' => 'id']);
    }




}
