<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\employee\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_employment_status".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \common\models\employee\HsHrEmployee[] $hsHrEmployees
 * @property \common\models\employee\HsHrJobtitEmpstat[] $hsHrJobtitEmpstats
 * @property \common\models\employee\OhrmJobTitle[] $jobtitCodes
 * @property string $aliasModel
 */
abstract class EmploymentStatus extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_employment_status';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 60]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmployees()
    {
        return $this->hasMany(\common\models\employee\HsHrEmployee::className(), ['emp_status' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrJobtitEmpstats()
    {
        return $this->hasMany(\common\models\employee\HsHrJobtitEmpstat::className(), ['estat_code' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobtitCodes()
    {
        return $this->hasMany(\common\models\employee\OhrmJobTitle::className(), ['id' => 'jobtit_code'])->viaTable('hs_hr_jobtit_empstat', ['estat_code' => 'id']);
    }




}
