<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\employee\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_emergency_contacts".
 *
 * @property integer $emp_number
 * @property string $eec_seqno
 * @property string $eec_name
 * @property string $eec_relationship
 * @property string $eec_home_no
 * @property string $eec_mobile_no
 * @property string $eec_office_no
 *
 * @property \common\models\employee\HsHrEmployee $empNumber
 * @property string $aliasModel
 */
abstract class Contacts extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_emergency_contacts';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['emp_number', 'eec_seqno'], 'required'],
            //[['emp_number'], 'integer'],
            [['eec_seqno'], 'number'],
            [['eec_name', 'eec_relationship', 'eec_home_no', 'eec_mobile_no', 'eec_office_no'], 'string', 'max' => 100],
            [['emp_number', 'eec_seqno'], 'unique', 'targetAttribute' => ['emp_number', 'eec_seqno']],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'emp_number' => 'Emp Number',
            'eec_seqno' => 'Eec Seqno',
            'eec_name' => 'Eec Name',
            'eec_relationship' => 'Eec Relationship',
            'eec_home_no' => 'Eec Home No',
            'eec_mobile_no' => 'Eec Mobile No',
            'eec_office_no' => 'Eec Office No',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\employee\Employee::className(), ['emp_number' => 'emp_number']);
    }




}
