<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_rotationResultTemp".
 *
 * @property integer $rotationId
 * @property string $rotationDate
 * @property integer $groupId
 * @property string $usersRecommend
 * @property string $usersRecommendUnselected
 * @property string $usersPrepareIn
 * @property string $usersPrepareOut
 * @property integer $rotationUserCount
 * @property string $aliasModel
 */
abstract class RotationResultTemp extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_rotationresulttemp';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rotationId'], 'required'],
            [['rotationId', 'groupId', 'rotationUserCount'], 'integer'],
            [['rotationDate'], 'safe'],
            [['usersRecommend', 'usersRecommendUnselected', 'usersPrepareIn', 'usersPrepareOut'], 'string', 'max' => 5000],
//            [['rotationId'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'rotationId' => 'Rotation ID',
            'rotationDate' => 'Rotation Date',
            'groupId' => 'Group ID',
            'usersRecommend' => 'Users Recommend',
            'usersRecommendUnselected' => 'Users Recommend Unselected',
            'usersPrepareIn' => 'Users Prepare In',
            'usersPrepareOut' => 'Users Prepare Out',
            'rotationUserCount' => 'Rotation User Count',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'rotationId' => '主键 不自增',
            'rotationDate' => '轮转日期
 例2018/1/1',
            'groupId' => '组id',
            'usersRecommend' => '满足条件的全部人串 格式json 注意顺序
  [{\"userId\": \"1\",\"userName\": \"A组满足人1\"},{\"userId\": \"2\",\"userName\": \"A组满足人2\"}]',
            'usersRecommendUnselected' => '满足条件的剩余人串 格式json 注意顺序',
            'usersPrepareIn' => '拟调入的人串 格式json 注意顺序',
            'usersPrepareOut' => '拟调出的人串 格式json 注意顺序',
            'rotationUserCount' => '轮转的人数 默认0',
        ]);
    }




}
