<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_rotary_employee".
 *
 * @property integer $id
 * @property integer $rotary_id
 * @property integer $emp_number
 * @property string $date_from
 * @property string $date_to
 * @property integer $orange_department_id
 * @property integer $rotary_department_id
 * @property string $aliasModel
 */
abstract class ShiftRotaryEmployee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_rotary_employee';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rotary_id', 'date_from', 'date_to'], 'required'],
            [['rotary_id', 'emp_number', 'orange_department_id', 'rotary_department_id'], 'integer'],
            [['date_from', 'date_to'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rotary_id' => 'Rotary ID',
            'emp_number' => 'Emp Number',
            'date_from' => 'Date From',
            'date_to' => 'Date To',
            'orange_department_id' => 'Orange Department ID',
            'rotary_department_id' => 'Rotary Department ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'orange_department_id' => '原先部门',
            'rotary_department_id' => '轮转后部门',
        ]);
    }




}
