<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\curriculum\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_curriculum_questions".
 *
 * @property string $id
 * @property string $name
 * @property string $fraction
 * @property string $firstuplod_id
 * @property string $create_time
 * @property integer $question_type
 *
 * @property \common\models\curriculum\OhrmCurriculumAnswer[] $ohrmCurriculumAnswers
 * @property \common\models\curriculum\OhrmCurriculumProblems[] $ohrmCurriculumProblems
 * @property string $aliasModel
 */
abstract class CurriculumQuestions extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_curriculum_questions';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['create_time'], 'safe'],
            [['name'], 'string', 'max' => 200],
            [['fraction'], 'string', 'max' => 20],
            [['firstuplod_id'], 'string', 'max' => 50],
            [['question_type'], 'string', 'max' => 4]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'fraction' => 'Fraction',
            'firstuplod_id' => 'Firstuplod ID',
            'create_time' => 'Create Time',
            'question_type' => 'Question Type',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => '考题名称',
            'fraction' => '分值',
            'firstuplod_id' => '第一次创建时的课程id',
            'create_time' => '创建时间',
            'question_type' => '考题类型  1单选 2多选 3图片单选 4图片多选 5填空 6简答',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmCurriculumAnswers()
    {
        return $this->hasMany(\common\models\curriculum\CurriculumAnswer::className(), ['question_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmCurriculumProblems()
    {
        return $this->hasMany(\common\models\curriculum\CurriculumProblems::className(), ['question_id' => 'id']);
    }




}
