<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\patent\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_patent".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property string $patent_name
 * @property integer $patent_class
 * @property integer $patent_type
 * @property string $department
 * @property string $applicant
 * @property string $patentee
 * @property string $authorization_time
 * @property string $accept_time
 * @property string $patent_number
 * @property string $apply_number
 * @property string $remarks
 * @property string $aliasModel
 */
abstract class Patent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_patent';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number'], 'integer'],
            [['authorization_time', 'accept_time'], 'safe'],
            [['patent_name', 'applicant', 'patentee', 'patent_number', 'apply_number'], 'string', 'max' => 100],
            [['patent_class', 'patent_type'], 'string', 'max' => 4],
            [['department', 'remarks'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'patent_name' => 'Patent Name',
            'patent_class' => 'Patent Class',
            'patent_type' => 'Patent Type',
            'department' => 'Department',
            'applicant' => 'Applicant',
            'patentee' => 'Patentee',
            'authorization_time' => 'Authorization Time',
            'accept_time' => 'Accept Time',
            'patent_number' => 'Patent Number',
            'apply_number' => 'Apply Number',
            'remarks' => 'Remarks',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'patent_name' => '专利名',
            'patent_class' => '专利种类  0：授权     1：申请',
            'patent_type' => '专利类型   0：发明类  1：实用新型',
            'department' => '科室',
            'applicant' => '申请人',
            'patentee' => '专利权人',
            'authorization_time' => '授权日',
            'accept_time' => '受理日',
            'patent_number' => '专利号',
            'apply_number' => '专利申请号',
            'remarks' => '备注',
        ]);
    }




}
