<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\employee\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_employee".
 *
 * @property integer $emp_number
 * @property string $employee_id
 * @property string $emp_lastname
 * @property string $emp_firstname
 * @property string $emp_middle_name
 * @property string $emp_nick_name
 * @property integer $emp_smoker
 * @property string $ethnic_race_code
 * @property string $emp_retire
 * @property string $emp_birthday
 * @property integer $nation_code
 * @property integer $minzu_code
 * @property string $weixin_code
 * @property integer $emp_gender
 * @property string $emp_marital_status
 * @property string $emp_ssn_num
 * @property string $emp_sin_num
 * @property string $emp_other_id
 * @property string $emp_dri_lice_num
 * @property string $emp_dri_lice_exp_date
 * @property string $emp_military_service
 * @property integer $emp_status
 * @property string $emp_politics
 * @property integer $job_title_code
 * @property integer $eeo_cat_code
 * @property string $eeo_cat_describe
 * @property string $emp_cost_center
 * @property integer $work_station
 * @property string $subunit_time
 * @property string $location_time
 * @property integer $last_depart
 * @property string $emp_street1
 * @property string $emp_street2
 * @property string $city_code
 * @property string $coun_code
 * @property string $provin_code
 * @property string $emp_zipcode
 * @property string $emp_zipcode2
 * @property string $emp_hm_telephone
 * @property string $emp_mobile
 * @property string $emp_work_telephone
 * @property string $emp_work_email
 * @property string $sal_grd_code
 * @property string $joined_date
 * @property string $incourtyard_date
 * @property string $probation_date
 * @property string $formal_date
 * @property string $emp_oth_email
 * @property integer $termination_id
 * @property string $custom1
 * @property string $custom2
 * @property string $custom3
 * @property string $custom4
 * @property string $custom5
 * @property string $custom6
 * @property string $custom7
 * @property string $custom8
 * @property string $custom9
 * @property string $custom10
 * @property integer $education_id
 * @property string $working_years
 * @property integer $licenses_id
 * @property integer $skills_id
 * @property string $mutual_exclusion
 * @property integer $department_id
 * @property integer $special_personnel
 * @property integer $contract_status
 * @property integer $attime_education
 * @property string $attime_graduation
 * @property string $attime_graduation_school
 * @property string $attime_studymajor
 * @property string $now_education
 * @property string $now_graduationtime
 * @property integer $now_academic_degree
 * @property string $now_academic_degreetime
 * @property string $now_graduation_school
 * @property string $join_party
 * @property integer $is_leader
 * @property integer $workload_ranking
 * @property integer $is_scheduling
 * @property integer $is_risk_ranking
 *
 * @property \common\models\employee\HsHrEmpBasicsalary[] $hsHrEmpBasicsalaries
 * @property \common\models\employee\HsHrEmpChildren[] $hsHrEmpChildrens
 * @property \common\models\employee\HsHrEmpContractExtend[] $hsHrEmpContractExtends
 * @property \common\models\employee\HsHrEmpDependents[] $hsHrEmpDependents
 * @property \common\models\employee\HsHrEmpEmergencyContacts[] $hsHrEmpEmergencyContacts
 * @property \common\models\employee\HsHrEmpHistoryOfEalierPos[] $hsHrEmpHistoryOfEalierPos
 * @property \common\models\employee\HsHrEmpLanguage[] $hsHrEmpLanguages
 * @property \common\models\employee\HsHrEmpLocations[] $hsHrEmpLocations
 * @property \common\models\employee\OhrmLocation[] $locations
 * @property \common\models\employee\HsHrEmpMemberDetail[] $hsHrEmpMemberDetails
 * @property \common\models\employee\OhrmMembership[] $membshipCodes
 * @property \common\models\employee\HsHrEmpPassport[] $hsHrEmpPassports
 * @property \common\models\employee\HsHrEmpPicture $hsHrEmpPicture
 * @property \common\models\employee\HsHrEmpReportto[] $hsHrEmpReporttos
 * @property \common\models\employee\HsHrEmpReportto[] $hsHrEmpReporttos0
 * @property \common\models\employee\HsHrEmpSkill[] $hsHrEmpSkills
 * @property \common\models\employee\HsHrEmpStructure[] $hsHrEmpStructures
 * @property \common\models\employee\HsHrEmpStructure[] $hsHrEmpStructures0
 * @property \common\models\employee\HsHrEmpUsTax $hsHrEmpUsTax
 * @property \common\models\employee\HsHrEmpWorkExperience[] $hsHrEmpWorkExperiences
 * @property \common\models\employee\OhrmSubunit $workStation
 * @property \common\models\employee\OhrmNationality $nationCode
 * @property \common\models\employee\OhrmJobTitle $jobTitleCode
 * @property \common\models\employee\OhrmEmploymentStatus $empStatus
 * @property \common\models\employee\OhrmJobCategory $eeoCatCode
 * @property \common\models\employee\OhrmEmpTermination $termination
 * @property \common\models\employee\OhrmEmpEducation[] $ohrmEmpEducations
 * @property \common\models\employee\OhrmEmpLicense[] $ohrmEmpLicenses
 * @property \common\models\employee\OhrmLicense[] $licenses
 * @property \common\models\employee\OhrmEmpTermination[] $ohrmEmpTerminations
 * @property \common\models\employee\OhrmEmployeeWorkShift[] $ohrmEmployeeWorkShifts
 * @property \common\models\employee\OhrmWorkShift[] $workShifts
 * @property \common\models\employee\OhrmJobCandidate[] $ohrmJobCandidates
 * @property \common\models\employee\OhrmJobCandidateHistory[] $ohrmJobCandidateHistories
 * @property \common\models\employee\OhrmJobInterviewInterviewer[] $ohrmJobInterviewInterviewers
 * @property \common\models\employee\OhrmJobInterview[] $interviews
 * @property \common\models\employee\OhrmJobVacancy[] $ohrmJobVacancies
 * @property \common\models\employee\OhrmLeaveAdjustment[] $ohrmLeaveAdjustments
 * @property \common\models\employee\OhrmLeaveComment[] $ohrmLeaveComments
 * @property \common\models\employee\OhrmLeaveEntitlement[] $ohrmLeaveEntitlements
 * @property \common\models\employee\OhrmLeaveRequest[] $ohrmLeaveRequests
 * @property \common\models\employee\OhrmLeaveRequestComment[] $ohrmLeaveRequestComments
 * @property \common\models\employee\OhrmOvertimeList[] $ohrmOvertimeLists
 * @property \common\models\employee\OhrmPerformanceReview[] $ohrmPerformanceReviews
 * @property \common\models\employee\OhrmPerformanceTrack[] $ohrmPerformanceTracks
 * @property \common\models\employee\OhrmPerformanceTrack[] $ohrmPerformanceTracks0
 * @property \common\models\employee\OhrmPerformanceTrackerLog[] $ohrmPerformanceTrackerLogs
 * @property \common\models\employee\OhrmPerformanceTrackerReviewer[] $ohrmPerformanceTrackerReviewers
 * @property \common\models\employee\OhrmProjectAdmin[] $ohrmProjectAdmins
 * @property \common\models\employee\OhrmProject[] $projects
 * @property \common\models\employee\OhrmUser[] $ohrmUsers
 * @property string $aliasModel
 */
abstract class Employee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_employee';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['emp_number'], 'required'],
//            [['emp_number', 'emp_smoker', 'nation_code', 'emp_gender', 'emp_status', 'job_title_code', 'eeo_cat_code', 'work_station', 'last_depart', 'termination_id'], 'integer'],
//            [['emp_retire', 'emp_birthday', 'emp_dri_lice_exp_date', 'subunit_time', 'location_time', 'joined_date', 'incourtyard_date', 'probation_date', 'formal_date', 'attime_graduation', 'now_graduationtime', 'now_academic_degreetime', 'join_party'], 'safe'],
//            [['employee_id', 'emp_politics', 'emp_hm_telephone', 'emp_mobile', 'emp_work_telephone', 'emp_work_email', 'emp_oth_email', 'working_years', 'mutual_exclusion'], 'string', 'max' => 50],
//            [['emp_lastname', 'emp_firstname', 'emp_middle_name', 'emp_nick_name', 'weixin_code', 'emp_ssn_num', 'emp_sin_num', 'emp_other_id', 'emp_dri_lice_num', 'emp_military_service', 'emp_street1', 'emp_street2', 'city_code', 'coun_code', 'provin_code', 'attime_graduation_school', 'attime_studymajor', 'now_education', 'now_graduation_school'], 'string', 'max' => 100],
//            [['ethnic_race_code', 'sal_grd_code'], 'string', 'max' => 13],
//            [['minzu_code'], 'string', 'max' => 2],
//            [['emp_marital_status', 'emp_zipcode', 'emp_zipcode2'], 'string', 'max' => 20],
//            [['eeo_cat_describe', 'emp_cost_center', 'custom1', 'custom2', 'custom3', 'custom4', 'custom5', 'custom6', 'custom7', 'custom8', 'custom9', 'custom10'], 'string', 'max' => 250],
            //[['education_id', 'licenses_id', 'skills_id', 'department_id', 'special_personnel', 'contract_status', 'attime_education', 'now_academic_degree'], 'string', 'max' => 4],
            //[['is_leader', 'workload_ranking', 'is_scheduling', 'is_risk_ranking'], 'string', 'max' => 1],
            //[['emp_number'], 'unique'],
            [['work_station'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\subunit\Subunit::className(), 'targetAttribute' => ['work_station' => 'id']],
            [['nation_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\user\Nationality::className(), 'targetAttribute' => ['nation_code' => 'id']],
            [['job_title_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\JobTitle::className(), 'targetAttribute' => ['job_title_code' => 'id']],
            [['emp_status'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\EmploymentStatus::className(), 'targetAttribute' => ['emp_status' => 'id']],
            [['eeo_cat_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\JobCategory::className(), 'targetAttribute' => ['eeo_cat_code' => 'id']],
            [['termination_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\EmpTermination::className(), 'targetAttribute' => ['termination_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'emp_number' => 'Emp Number',
            'employee_id' => 'Employee ID',
            'emp_lastname' => 'Emp Lastname',
            'emp_firstname' => 'Emp Firstname',
            'emp_middle_name' => 'Emp Middle Name',
            'emp_nick_name' => 'Emp Nick Name',
            'emp_smoker' => 'Emp Smoker',
            'ethnic_race_code' => 'Ethnic Race Code',
            'emp_retire' => 'Emp Retire',
            'emp_birthday' => 'Emp Birthday',
            'nation_code' => 'Nation Code',
            'minzu_code' => 'Minzu Code',
            'weixin_code' => 'Weixin Code',
            'emp_gender' => 'Emp Gender',
            'emp_marital_status' => 'Emp Marital Status',
            'emp_ssn_num' => 'Emp Ssn Num',
            'emp_sin_num' => 'Emp Sin Num',
            'emp_other_id' => 'Emp Other ID',
            'emp_dri_lice_num' => 'Emp Dri Lice Num',
            'emp_dri_lice_exp_date' => 'Emp Dri Lice Exp Date',
            'emp_military_service' => 'Emp Military Service',
            'emp_status' => 'Emp Status',
            'emp_politics' => 'Emp Politics',
            'job_title_code' => 'Job Title Code',
            'eeo_cat_code' => 'Eeo Cat Code',
            'eeo_cat_describe' => 'Eeo Cat Describe',
            'emp_cost_center' => 'Emp Cost Center',
            'work_station' => 'Work Station',
            'subunit_time' => 'Subunit Time',
            'location_time' => 'Location Time',
            'last_depart' => 'Last Depart',
            'emp_street1' => 'Emp Street1',
            'emp_street2' => 'Emp Street2',
            'city_code' => 'City Code',
            'coun_code' => 'Coun Code',
            'provin_code' => 'Provin Code',
            'emp_zipcode' => 'Emp Zipcode',
            'emp_zipcode2' => 'Emp Zipcode2',
            'emp_hm_telephone' => 'Emp Hm Telephone',
            'emp_mobile' => 'Emp Mobile',
            'emp_work_telephone' => 'Emp Work Telephone',
            'emp_work_email' => 'Emp Work Email',
            'sal_grd_code' => 'Sal Grd Code',
            'joined_date' => 'Joined Date',
            'incourtyard_date' => 'Incourtyard Date',
            'probation_date' => 'Probation Date',
            'formal_date' => 'Formal Date',
            'emp_oth_email' => 'Emp Oth Email',
            'termination_id' => 'Termination ID',
            'custom1' => 'Custom1',
            'custom2' => 'Custom2',
            'custom3' => 'Custom3',
            'custom4' => 'Custom4',
            'custom5' => 'Custom5',
            'custom6' => 'Custom6',
            'custom7' => 'Custom7',
            'custom8' => 'Custom8',
            'custom9' => 'Custom9',
            'custom10' => 'Custom10',
            'education_id' => 'Education ID',
            'working_years' => 'Working Years',
            'licenses_id' => 'Licenses ID',
            'skills_id' => 'Skills ID',
            'mutual_exclusion' => 'Mutual Exclusion',
            'department_id' => 'Department ID',
            'special_personnel' => 'Special Personnel',
            'contract_status' => 'Contract Status',
            'attime_education' => 'Attime Education',
            'attime_graduation' => 'Attime Graduation',
            'attime_graduation_school' => 'Attime Graduation School',
            'attime_studymajor' => 'Attime Studymajor',
            'now_education' => 'Now Education',
            'now_graduationtime' => 'Now Graduationtime',
            'now_academic_degree' => 'Now Academic Degree',
            'now_academic_degreetime' => 'Now Academic Degreetime',
            'now_graduation_school' => 'Now Graduation School',
            'join_party' => 'Join Party',
            'is_leader' => 'Is Leader',
            'workload_ranking' => 'Workload Ranking',
            'is_scheduling' => 'Is Scheduling',
            'is_risk_ranking' => 'Is Risk Ranking',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'employee_id' => '员工识别号',
            'emp_firstname' => '姓名  中国习惯 把第一个名称用作全名',
            'emp_retire' => '退休日期',
            'emp_birthday' => '生日',
            'nation_code' => '国家 代号',
            'minzu_code' => '民族编号',
            'weixin_code' => '微信号',
            'emp_gender' => '性别',
            'emp_marital_status' => '婚姻状态',
            'emp_other_id' => '身份证号',
            'emp_politics' => '政治面貌',
            'job_title_code' => '职称id',
            'eeo_cat_code' => '岗位名称',
            'eeo_cat_describe' => '岗位描述',
            'emp_cost_center' => '成本中心',
            'work_station' => '子组',
            'subunit_time' => '进组时间',
            'location_time' => '进部门时间',
            'last_depart' => '上一个部门id',
            'emp_street1' => '身份证户籍邮编',
            'emp_street2' => '居住地邮编',
            'emp_zipcode' => '户籍邮编',
            'emp_zipcode2' => '居住地邮编',
            'joined_date' => '入职时间',
            'incourtyard_date' => '进院时间',
            'probation_date' => '试用期截止日期',
            'formal_date' => '转正日期',
            'education_id' => '学历id',
            'working_years' => '工龄',
            'licenses_id' => '执业资格 id',
            'skills_id' => '执业技能id',
            'mutual_exclusion' => '互斥人员',
            'department_id' => '部门id  (暂时不需要了)',
            'special_personnel' => '是否特殊人员 0 无 1孕妇 2其他',
            'contract_status' => '合同状态 1正式工 2临时工 3实习生',
            'attime_education' => '进院时学历',
            'attime_graduation' => '毕业时间',
            'attime_graduation_school' => '毕业学校',
            'attime_studymajor' => '所学专业',
            'now_education' => '现在学历  (作废 使用education_id代替)',
            'now_graduationtime' => '现学历毕业时间',
            'now_academic_degree' => '现学位',
            'now_academic_degreetime' => '现学位毕业时间',
            'now_graduation_school' => '现学历毕业学校',
            'join_party' => '入党时间',
            'is_leader' => '是否是组长 1 是 0 否',
            'workload_ranking' => '是否参与工作量分配 1参与 0不参与',
            'is_scheduling' => '是否参与排班 1 参与 0不参与',
            'is_risk_ranking' => '是否参与风险金分配 1参与 0不参与',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpBasicsalaries()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpBasicsalary::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpChildrens()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpChildren::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpContractExtends()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpContractExtend::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpDependents()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpDependents::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpEmergencyContacts()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpEmergencyContacts::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpHistoryOfEalierPos()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpHistoryOfEalierPos::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpLanguages()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpLanguage::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpLocations()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpLocations::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocations()
    {
        return $this->hasMany(\common\models\employee\OhrmLocation::className(), ['id' => 'location_id'])->viaTable('hs_hr_emp_locations', ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpMemberDetails()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpMemberDetail::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMembshipCodes()
    {
        return $this->hasMany(\common\models\employee\OhrmMembership::className(), ['id' => 'membship_code'])->viaTable('hs_hr_emp_member_detail', ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpPassports()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpPassport::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpPicture()
    {
        return $this->hasOne(\common\models\employee\HsHrEmpPicture::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpReporttos()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpReportto::className(), ['erep_sup_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpReporttos0()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpReportto::className(), ['erep_sub_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpSkills()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpSkill::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpStructures()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpStructure::className(), ['erep_sup_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpStructures0()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpStructure::className(), ['erep_sub_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpUsTax()
    {
        return $this->hasOne(\common\models\employee\HsHrEmpUsTax::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmpWorkExperiences()
    {
        return $this->hasMany(\common\models\employee\HsHrEmpWorkExperience::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubunit()
    {
        return $this->hasOne(\common\models\subunit\Subunit::className(), ['id' => 'work_station']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNationCode()
    {
        return $this->hasOne(\common\models\employee\OhrmNationality::className(), ['id' => 'nation_code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJobTitleCode()
    {
        return $this->hasOne(\common\models\employee\OhrmJobTitle::className(), ['id' => 'job_title_code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpStatus()
    {
        return $this->hasOne(\common\models\employee\OhrmEmploymentStatus::className(), ['id' => 'emp_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEeoCatCode()
    {
        return $this->hasOne(\common\models\employee\OhrmJobCategory::className(), ['id' => 'eeo_cat_code']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTermination()
    {
        return $this->hasOne(\common\models\employee\OhrmEmpTermination::className(), ['id' => 'termination_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpEducation()
    {
        return $this->hasMany(\common\models\employee\EmpEducation::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducation()
    {
        return $this->hasOne(\common\models\employee\Education::className(), ['id' => 'termination_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmpLicenses()
    {
        return $this->hasMany(\common\models\employee\OhrmEmpLicense::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLicenses()
    {
        return $this->hasMany(\common\models\employee\OhrmLicense::className(), ['id' => 'license_id'])->viaTable('ohrm_emp_license', ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmpTerminations()
    {
        return $this->hasMany(\common\models\employee\OhrmEmpTermination::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmployeeWorkShifts()
    {
        return $this->hasMany(\common\models\employee\OhrmEmployeeWorkShift::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkShifts()
    {
        return $this->hasMany(\common\models\employee\OhrmWorkShift::className(), ['id' => 'work_shift_id'])->viaTable('ohrm_employee_work_shift', ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobCandidates()
    {
        return $this->hasMany(\common\models\employee\OhrmJobCandidate::className(), ['added_person' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobCandidateHistories()
    {
        return $this->hasMany(\common\models\employee\OhrmJobCandidateHistory::className(), ['performed_by' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobInterviewInterviewers()
    {
        return $this->hasMany(\common\models\employee\OhrmJobInterviewInterviewer::className(), ['interviewer_id' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInterviews()
    {
        return $this->hasMany(\common\models\employee\OhrmJobInterview::className(), ['id' => 'interview_id'])->viaTable('ohrm_job_interview_interviewer', ['interviewer_id' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmJobVacancies()
    {
        return $this->hasMany(\common\models\employee\OhrmJobVacancy::className(), ['hiring_manager_id' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveAdjustments()
    {
        return $this->hasMany(\common\models\employee\OhrmLeaveAdjustment::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveComments()
    {
        return $this->hasMany(\common\models\employee\OhrmLeaveComment::className(), ['created_by_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveEntitlements()
    {
        return $this->hasMany(\common\models\employee\OhrmLeaveEntitlement::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveRequests()
    {
        return $this->hasMany(\common\models\employee\OhrmLeaveRequest::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmLeaveRequestComments()
    {
        return $this->hasMany(\common\models\employee\OhrmLeaveRequestComment::className(), ['created_by_emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmOvertimeLists()
    {
        return $this->hasMany(\common\models\employee\OhrmOvertimeList::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceReviews()
    {
        return $this->hasMany(\common\models\employee\OhrmPerformanceReview::className(), ['employee_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceTracks()
    {
        return $this->hasMany(\common\models\employee\OhrmPerformanceTrack::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceTracks0()
    {
        return $this->hasMany(\common\models\employee\OhrmPerformanceTrack::className(), ['added_by' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceTrackerLogs()
    {
        return $this->hasMany(\common\models\employee\OhrmPerformanceTrackerLog::className(), ['reviewer_id' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmPerformanceTrackerReviewers()
    {
        return $this->hasMany(\common\models\employee\OhrmPerformanceTrackerReviewer::className(), ['reviewer_id' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmProjectAdmins()
    {
        return $this->hasMany(\common\models\employee\OhrmProjectAdmin::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(\common\models\employee\OhrmProject::className(), ['project_id' => 'project_id'])->viaTable('ohrm_project_admin', ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\user\User::className(), ['emp_number' => 'emp_number']);
    }




}
