<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\user\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_rotary_record".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $orange_department
 * @property integer $new_department
 * @property string $time_in
 * @property string $time_out
 * @property string $total_month
 * @property string $create_at
 * @property string $update_at
 * @property string $tmpclassname
 * @property string $tmpyear
 * @property string $tmpgongzihao
 * @property string $aliasModel
 */
abstract class Record extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_rotary_record';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'orange_department', 'new_department','total_month'], 'integer'],
            [['time_in', 'time_out', 'create_at', 'update_at'], 'safe'],
            [[ 'tmpclassname', 'tmpyear', 'tmpgongzihao'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'orange_department' => 'Orange Department',
            'new_department' => 'New Department',
            'time_in' => 'Time In',
            'time_out' => 'Time Out',
            'total_month' => 'Total Month',
            'create_at' => 'Create At',
            'update_at' => 'Update At',
            'tmpclassname' => 'Tmpclassname',
            'tmpyear' => 'Tmpyear',
            'tmpgongzihao' => 'Tmpgongzihao',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => '索引',
            'emp_number' => '员工号',
            'orange_department' => '变组前部门id',
            'new_department' => '新组',
            'time_in' => '进组时间',
            'time_out' => '出组时间',
            'total_month' => '总共多少个月',
            'create_at' => '该条数据创建时间',
            'update_at' => '该条数据更新时间',
        ]);
    }




}
