<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\performance\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_bonus_calculation_config".
 *
 * @property integer $id
 * @property integer $groupId
 * @property string $customerId
 * @property string $salarySheetField
 * @property string $aliasModel
 */
abstract class BonusCalculationConfig extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_bonus_calculation_config';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['groupId'], 'integer'],
            [['customerId'], 'string', 'max' => 255],
            [['salarySheetField'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'groupId' => 'Group ID',
            'customerId' => 'Customer ID',
            'salarySheetField' => 'Salary Sheet Field',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'salarySheetField' => '组员可以看到的列',
        ]);
    }




}
