<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_emp_skill".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $skill_id
 * @property string $years_of_exp
 * @property string $comments
 * @property integer $work_station
 *
 * @property \common\models\shift\HsHrEmployee $empNumber
 * @property \common\models\shift\OhrmSkill $skill
 * @property string $aliasModel
 */
abstract class EmpSkill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_emp_skill';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'skill_id', 'work_station'], 'integer'],
            [['years_of_exp'], 'number'],
            [['comments'], 'string', 'max' => 100],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\Employee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']],
            [['skill_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\Skill::className(), 'targetAttribute' => ['skill_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'skill_id' => 'Skill ID',
            'years_of_exp' => 'Years Of Exp',
            'comments' => 'Comments',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'work_station' => '所属小组',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\shift\Employee::className(), ['emp_number' => 'emp_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSkill()
    {
        return $this->hasOne(\common\models\shift\Skill::className(), ['id' => 'skill_id']);
    }




}
