<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_rotationRuleWarehouse".
 *
 * @property integer $id
 * @property string $ruleType
 * @property string $ruleTypeName
 * @property string $ruleTitle
 * @property string $select1
 * @property string $select2
 * @property string $input1
 * @property string $input2
 * @property integer $isMultiple
 * @property integer $status
 * @property string $aliasModel
 */
abstract class RotationRuleWarehouse extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_rotationrulewarehouse';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ruleType'], 'required'],
            [['status'], 'integer'],
            [['ruleType', 'ruleTypeName', 'ruleTitle', 'input1', 'input2'], 'string', 'max' => 50],
            [['select1', 'select2'], 'string', 'max' => 500],
            [['isMultiple'], 'string', 'max' => 4]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ruleType' => 'Rule Type',
            'ruleTypeName' => 'Rule Type Name',
            'ruleTitle' => 'Rule Title',
            'select1' => 'Select1',
            'select2' => 'Select2',
            'input1' => 'Input1',
            'input2' => 'Input2',
            'isMultiple' => 'Is Multiple',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => '主键',
            'ruleType' => '规则类型：空默认out调出规则in调入规则',
            'ruleTypeName' => '规则类型名称 例调出规则 调入规则',
            'ruleTitle' => '规则名称 例夫妻不能在一组',
            'select1' => '存放下拉框数据 格式json',
            'select2' => '存放下拉框数据 格式json',
            'input1' => '存放输入框数据 格式json',
            'input2' => '存放输入框数据 格式json',
            'isMultiple' => '是否可多条 0默认1可多条',
            'status' => '状态：0默认1开放2关闭',
        ]);
    }




}
