<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_rotationdown".
 *
 * @property integer $id
 * @property integer $outuserId
 * @property string $outuserName
 * @property integer $outgroupId
 * @property string $outgroupName
 * @property integer $work_time
 * @property integer $inuserId
 * @property string $inuserName
 * @property integer $ingroupId
 * @property string $ingroupName
 * @property string $aliasModel
 */
abstract class RotationDown extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_rotationdown';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['outuserId', 'outgroupId', 'work_time', 'inuserId', 'ingroupId'], 'integer'],
            [['outuserName', 'outgroupName', 'inuserName', 'ingroupName'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'outuserId' => 'Outuser ID',
            'outuserName' => 'Outuser Name',
            'outgroupId' => 'Outgroup ID',
            'outgroupName' => 'Outgroup Name',
            'work_time' => 'Work Time',
            'inuserId' => 'Inuser ID',
            'inuserName' => 'Inuser Name',
            'ingroupId' => 'Ingroup ID',
            'ingroupName' => 'Ingroup Name',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => '主键',
            'outuserId' => '调出人id',
            'outuserName' => '调出姓名',
            'outgroupId' => '调出组id',
            'outgroupName' => '调出组名字',
            'work_time' => '在组内时间',
            'inuserId' => '进入人id',
            'inuserName' => '进入人姓名',
            'ingroupId' => '进入组id',
            'ingroupName' => '进入组名字',
        ]);
    }




}
