<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_type".
 *
 * @property integer $id
 * @property string $create_at
 * @property integer $schedule_id
 * @property string $name
 * @property string $start_time
 * @property string $end_time
 * @property integer $skill_id
 * @property string $status
 * @property integer $copy_type
 * @property integer $require_employee
 * @property integer $is_grant
 * @property integer $is_night_shift
 * @property double $duty_factor
 * @property integer $is_amont_work
 * @property integer $location_id
 * @property string $week_select
 *
 * @property \common\models\OhrmWorkShift[] $ohrmWorkShifts
 * @property \common\models\OhrmWorkSchedule $schedule
 * @property \common\models\OhrmWorkTypeSkill[] $ohrmWorkTypeSkills
 * @property string $aliasModel
 */
abstract class ShiftType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_type';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // [['name','duty_factor','create_at', 'start_time', 'end_time','is_grant', 'is_night_shift', 'is_amont_work','require_employee', 'location_id','week_select'], 'required'],
            [['create_at', 'start_time', 'end_time'], 'required'],
            [['name','require_employee','week_select'], 'required'],
            [['duty_factor','is_grant', 'is_night_shift','is_amont_work'], 'required'],
        
            [['create_at'], 'date','format' => 'yyyy-mm-dd'],
            [['start_time','end_time','time_start_third','time_end_third','start_time_afternoon','end_time_afternoon'], 'datetime','format' => 'HH:mm'],
            [['id','create_at','start_time','end_time'], 'safe'],
            [['schedule_id', 'copy_type', 'require_employee', 'location_id','is_approval','is_work_overtime'], 'integer'],
            [['duty_factor'], 'number'],
            [['name', 'status','remark','color'], 'string', 'max' => 250],
            [['is_grant', 'is_night_shift', 'is_amont_work'], 'string', 'max' => 4],
            [['week_select','skill_id'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'create_at' => 'Create At',
            'schedule_id' => 'Schedule ID',
            'name' => 'Name',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'skill_id' => 'Skill ID',
            'status' => 'Status',
            'copy_type' => 'Copy Type',
            'require_employee' => 'Require Employee',
            'is_grant' => 'Is Grant',
            'is_night_shift' => 'Is Night Shift',
            'duty_factor' => 'Duty Factor',
            'is_amont_work' => 'Is Amont Work',
            'location_id' => 'Location ID',
            'week_select' => 'Week Select',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => '排班类型名',
            'skill_id' => '岗位所需要技能',
            'is_grant' => '是否需要补助金 1是 0 否',
            'is_night_shift' => '是否夜班 1是 0 否',
            'duty_factor' => '工作系数',
            'is_amont_work' => '是否添加工作量 1添加 0不添加',
            'location_id' => '部门ID',
            'week_select' => '自定义周几排班',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkShifts()
    {
        return $this->hasMany(\common\models\shift\Shift::className(), ['shift_type_id' => 'id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmWorkTypeSkills()
    {
        return $this->hasMany(\common\models\shift\TypeSkill::className(), ['shift_type_id' => 'id']);
    }

}
