<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift".
 *
 * @property integer $id
 * @property string $name
 * @property string $hours_per_day
 * @property string $start_time
 * @property string $end_time
 * @property integer $schedule_id
 * @property integer $shift_type_id
 * @property integer $shiftdate_id
 * @property integer $required_employee
 * @property string $status
 * @property string $create_at
 *
 * @property \common\models\OhrmEmployeeWorkShift[] $ohrmEmployeeWorkShifts
 * @property \common\models\HsHrEmployee[] $empNumbers
 * @property \common\models\Schedule $schedule
 * @property \common\models\ShiftType $shiftType
 * @property \common\models\ShiftAssignment[] $ShiftAssignments
 * @property string $aliasModel
 */
abstract class Shift extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'start_time', 'end_time', 'create_at'], 'required'],
            [['hours_per_day'], 'number'],
            [['start_time', 'end_time', 'create_at'], 'safe'],
            [['schedule_id', 'shift_type_id', 'shiftdate_id', 'required_employee'], 'integer'],
            [['name', 'status'], 'string', 'max' => 250],
            [['schedule_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\Schedule::className(), 'targetAttribute' => ['schedule_id' => 'id']],
            [['shift_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\ShiftType::className(), 'targetAttribute' => ['shift_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'hours_per_day' => 'Hours Per Day',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'schedule_id' => 'Schedule ID',
            'shift_type_id' => 'Shift Type ID',
            'shiftdate_id' => 'Shiftdate ID',
            'required_employee' => 'Required Employee',
            'status' => 'Status',
            'create_at' => 'Create At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'schedule_id' => '排班计划id',
            'shift_type_id' => '排班类型ID',
            'shiftdate_id' => '轮班日期id',
            'required_employee' => '排班所需人数',
            'status' => '状态值',
            'create_at' => '创建时间',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmEmployeeWorkShifts()
    {
        return $this->hasMany(\common\models\OhrmEmployeeWorkShift::className(), ['work_shift_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumbers()
    {
        return $this->hasMany(\common\models\HsHrEmployee::className(), ['emp_number' => 'emp_number'])->viaTable('ohrm_employee_work_shift', ['work_shift_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedule()
    {
        return $this->hasOne(\common\models\shift\Schedule::className(), ['id' => 'schedule_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShiftType()
    {
        return $this->hasOne(\common\models\shift\ShiftType::className(), ['id' => 'shift_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShiftAssignments()
    {
        return $this->hasMany(\common\models\shift\ShiftAssignment::className(), ['shift_id' => 'id']);
    }




}
