<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_rotary".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_from
 * @property string $date_to
 * @property integer $first_department_id
 * @property integer $second_department_id
 * @property integer $third_department_id
 * @property integer $status
 * @property string $aliasModel
 */
abstract class ShiftRotary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_rotary';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'date_from', 'date_to', 'first_department_id', 'second_department_id', 'third_department_id'], 'required'],
            [['date_from', 'date_to'], 'safe'],
            [['first_department_id', 'second_department_id', 'third_department_id', 'status'], 'integer'],
            [['name'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'date_from' => 'Date From',
            'date_to' => 'Date To',
            'first_department_id' => 'First Department ID',
            'second_department_id' => 'Second Department ID',
            'third_department_id' => 'Third Department ID',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'status' => '1,展示，0删除',
        ]);
    }




}
