<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_shift_assignment".
 *
 * @property integer $id
 * @property integer $schedule_id
 * @property integer $shift_id
 * @property integer $shift_index
 * @property integer $shift_type_id
 * @property integer $shift_date
 * @property integer $work_station
 *
 * @property \common\models\shift\OhrmWorkSchedule $schedule
 * @property \common\models\shift\OhrmWorkShift $shift
 * @property string $aliasModel
 */
abstract class ShiftAssignment extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_shift_assignment';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['schedule_id', 'shift_date'], 'required'],
            [['schedule_id', 'shift_id', 'shift_index', 'shift_type_id', 'shift_date', 'work_station'], 'integer'],
            [['schedule_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\Schedule::className(), 'targetAttribute' => ['schedule_id' => 'id']],
            [['shift_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\Shift::className(), 'targetAttribute' => ['shift_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'schedule_id' => 'Schedule ID',
            'shift_id' => 'Shift ID',
            'shift_index' => 'Shift Index',
            'shift_type_id' => 'Shift Type ID',
            'shift_date' => 'Shift Date',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'shift_id' => '岗位所需要技能',
            'shift_index' => 'shiftid出现的次数',
            'shift_type_id' => '班次类型',
            'work_station' => '所在小组',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedule()
    {
        return $this->hasOne(\common\models\shift\Schedule::className(), ['id' => 'schedule_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShift()
    {
        return $this->hasOne(\common\models\shift\Shift::className(), ['id' => 'shift_id']);
    }




}
