<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_work_type_skill".
 *
 * @property integer $id
 * @property integer $shift_type_id
 * @property integer $skill_id
 * @property integer $work_station
 *
 * @property \common\models\OhrmWorkShiftType $shiftType
 * @property string $aliasModel
 */
abstract class TypeSkill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_work_type_skill';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shift_type_id', 'skill_id', 'work_station'], 'integer'],
            [['shift_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\shift\ShiftType::className(), 'targetAttribute' => ['shift_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shift_type_id' => 'Shift Type ID',
            'skill_id' => 'Skill ID',
            'work_station' => 'Work Station',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'shift_type_id' => '排班类型',
            'skill_id' => '该班所需要岗位',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShiftType()
    {
        return $this->hasOne(\common\models\shift\ShiftType::className(), ['id' => 'shift_type_id']);
    }




}
