<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\education\base;

use Yii;

/**
 * This is the base-model class for table "hs_hr_education".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $student_id
 * @property integer $type_id
 * @property string $start_time
 * @property string $end_time
 * @property string $content
 *
 * @property \common\models\EducationType $type
 * @property string $aliasModel
 */
abstract class Education extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hs_hr_education';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'emp_number', 'student_id', 'type_id'], 'integer'],
            [['start_time', 'end_time'], 'safe'],
            [['content'], 'string'],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\education\EducationType::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'student_id' => 'Student ID',
            'type_id' => 'Type ID',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'content' => 'Content',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'emp_number' => '带教人id',
            'student_id' => '学生姓名id',
            'type_id' => '学生类别',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'content' => '带教内容',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\common\models\education\EducationType::className(), ['id' => 'type_id']);
    }




}
