<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\system\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_user_role".
 *
 * @property integer $id
 * @property string $name
 * @property string $display_name
 * @property integer $is_assignable
 * @property integer $is_predefined
 *
 * @property \common\models\OhrmHomePage[] $ohrmHomePages
 * @property \common\models\OhrmModuleDefaultPage[] $ohrmModuleDefaultPages
 * @property \common\models\OhrmUser[] $ohrmUsers
 * @property \common\models\OhrmUserRoleDataGroup[] $ohrmUserRoleDataGroups
 * @property \common\models\OhrmUserRoleScreen[] $ohrmUserRoleScreens
 * @property string $aliasModel
 */
abstract class SystemUserRole extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_user_role';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'display_name'], 'required'],
            [['name', 'display_name'], 'string', 'max' => 255],
            [['is_assignable', 'is_predefined'], 'string', 'max' => 1],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'display_name' => 'Display Name',
            'is_assignable' => 'Is Assignable',
            'is_predefined' => 'Is Predefined',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmHomePages()
    {
        return $this->hasMany(\common\models\OhrmHomePage::className(), ['user_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmModuleDefaultPages()
    {
        return $this->hasMany(\common\models\OhrmModuleDefaultPage::className(), ['user_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSystemUsers()
    {
        return $this->hasMany(\common\models\system\SystemUser::className(), ['user_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmUserRoleDataGroups()
    {
        return $this->hasMany(\common\models\OhrmUserRoleDataGroup::className(), ['user_role_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOhrmUserRoleScreens()
    {
        return $this->hasMany(\common\models\OhrmUserRoleScreen::className(), ['user_role_id' => 'id']);
    }




}
