<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\employee\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_emp_termination".
 *
 * @property integer $id
 * @property integer $emp_number
 * @property integer $reason_id
 * @property string $termination_date
 * @property string $note
 *
 * @property \common\models\employee\HsHrEmployee[] $hsHrEmployees
 * @property \common\models\employee\OhrmEmpTerminationReason $reason
 * @property \common\models\employee\HsHrEmployee $empNumber
 * @property string $aliasModel
 */
abstract class EmpTermination extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_emp_termination';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['emp_number', 'reason_id'], 'integer'],
            [['termination_date'], 'required'],
            [['termination_date'], 'safe'],
            [['note'], 'string', 'max' => 255],
            [['reason_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\OhrmEmpTerminationReason::className(), 'targetAttribute' => ['reason_id' => 'id']],
            [['emp_number'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\employee\HsHrEmployee::className(), 'targetAttribute' => ['emp_number' => 'emp_number']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'emp_number' => 'Emp Number',
            'reason_id' => 'Reason ID',
            'termination_date' => 'Termination Date',
            'note' => 'Note',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHsHrEmployees()
    {
        return $this->hasMany(\common\models\employee\HsHrEmployee::className(), ['termination_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReason()
    {
        return $this->hasOne(\common\models\employee\OhrmEmpTerminationReason::className(), ['id' => 'reason_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpNumber()
    {
        return $this->hasOne(\common\models\employee\HsHrEmployee::className(), ['emp_number' => 'emp_number']);
    }




}
