<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\shift\base;

use Yii;

/**
 * This is the base-model class for table "ohrm_rotationVersion".
 *
 * @property integer $id
 * @property string $versionName
 * @property integer $rotationId
 * @property integer $status
 * @property string $aliasModel
 */
abstract class RotationVersion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ohrm_rotationversion';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('orangehrm');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rotationId', 'status'], 'integer'],
            [['versionName'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'versionName' => 'Version Name',
            'rotationId' => 'Rotation ID',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => '主键',
            'versionName' => '模板名称',
            'rotationId' => '轮转表（rotationList）',
            'status' => '状态：0默认1已发布2已删除',
        ]);
    }




}
